mod context;
mod gen_bitfld;
mod gen_dynarr;
mod gen_enum;
mod gen_fixedarr;
mod gen_pack;
mod gen_seq;
mod gen_var;
mod util;

use anyhow::Result;

use context::RustContext;

use crate::compile::{Type, TypeID, TypeKind, World};

use super::*;

/// Emits a Rust module for the given compiled `World`.
pub fn emit(world: &World, global: &GlobalOptions, out: &mut Outfile) -> Result<()> {
    let ctx = RustContext::new(world, global)?;

    emit_preamble(global, out);
    out.newline();

    emit_impl(&ctx, out)?;

    Ok(())
}

const PREFIX: &str = "

pub trait JawRead : Sized {
    fn jaw_read<R: Read>(reader: &mut R) -> io::Result<Self>;
}

pub trait JawWrite {
    fn jaw_write<W: Write>(&self, writer: &mut W) -> io::Result<()>;
}

";

/// Emits top-level imports and shared helpers for generated Rust.
fn emit_preamble(global: &GlobalOptions, out: &mut impl Sink) {
    out.wln("// Generated by jaw. Do not edit.");
    out.wln("use std::io::{self, Read, Write};");
    out.wln("use std::convert::TryInto;");

    out.newline();

    if let Some(path) = &global.rust_share_traits {
        out.wln(&format!("use {path}::{{JawRead, JawWrite}};"));
    } else {
        out.wln(PREFIX);

        for ty in [
            "u8", "i8", "u16", "i16", "u32", "i32", "u64", "i64", "f32", "f64",
        ] {
            out.wln(&format!("impl JawRead for {ty}"));
            {
                let mut idt = out.indent();

                idt.wln("#[inline]");
                idt.wln("fn jaw_read<R: Read>(reader: &mut R) -> io::Result<Self>");
                {
                    let mut idt = idt.indent();
                    idt.wln(&format!(
                        "let mut buf = [0u8; std::mem::size_of::<{ty}>()];"
                    ));
                    idt.wln("reader.read_exact(&mut buf)?;");
                    idt.wln(&format!("Ok({ty}::from_le_bytes(buf))"));
                }
            }

            out.wln(&format!("impl JawWrite for {ty}"));
            {
                let mut idt = out.indent();

                idt.wln("#[inline]");
                idt.wln("fn jaw_write<W: Write>(&self, writer: &mut W) -> io::Result<()>");
                {
                    let mut idt = idt.indent();
                    idt.wln("writer.write_all(&self.to_le_bytes())");
                }
            }
        }

        out.newline();
    }

    out.wln("fn invalid_data(msg: impl Into<String>) -> io::Error");
    {
        let mut idt = out.indent();
        idt.wln("io::Error::new(io::ErrorKind::InvalidData, msg.into())");
    }
    out.newline();
}

/// Emits a `read` or `write` module (types + impls) for the compiled `World`.
fn emit_impl(ctx: &RustContext, out: &mut impl Sink) -> Result<()> {
    out.newline();

    for (id, ty) in ctx.types() {
        emit_for(ctx, out, id, ty)?
    }

    Ok(())
}

/// Emits owned Rust type definitions used by the `read` module.
fn emit_for(ctx: &RustContext, out: &mut impl Sink, id: TypeID, ty: &Type) -> Result<()> {
    match &ty.kind {
        TypeKind::Enum(enm) => {
            gen_enum::emit_enum(ctx, out, id, ty, enm)?;
        }
        TypeKind::Bitfld(bitfld) => {
            gen_bitfld::emit_bitfld(ctx, out, id, ty, bitfld)?;
        }
        TypeKind::Pack(pack) => {
            gen_pack::emit_pack(ctx, out, id, ty, pack)?;
        }
        TypeKind::Sequence(seq) => {
            gen_seq::emit_seq(ctx, out, id, ty, seq)?;
        }
        TypeKind::Variant(variant) => {
            gen_var::emit_var(ctx, out, id, ty, variant)?;
        }
        TypeKind::DynamicArray(arr) => {
            gen_dynarr::emit_dynarr(ctx, out, id, ty, arr)?;
        }
        TypeKind::FixedArray(arr) => {
            gen_fixedarr::emit_fixedarr(ctx, out, id, ty, arr)?;
        }
        TypeKind::Primitive(_) | TypeKind::Void => {}
    }

    Ok(())
}
