//! C++ backend: emits a single header containing types and helpers.
//!
//! Highlights
//! - `read`/`write` free functions parameterized by a `Reader`/`Writer` concept
//!   (provides `read_raw`/`write_raw`).
//! - For sequences and variants, also emits `<Name>View` types so callers can
//!   write directly from pointers/spans without constructing full values.
use crate::{module::*, tokens::Span};
use crate::codegen::common::{TextEmitter, sanitize_ident};
use std::fmt::Write;

/// Public entry: emit a single header string with all types and read/write helpers.
pub fn emit_cpp_header(
    module: Module,
    mut file: impl std::io::Write,
) -> Result<(), super::GeneratorError> {
    let mut e = CppEmitter::new(&module);
    e.emit_preamble();
    e.emit_all_types();
    let string = e.finish();

    file.write_all(string.as_bytes())?;

    Ok(())
}

struct CppEmitter<'a> { e: TextEmitter<'a> }

impl<'a> CppEmitter<'a> {
    fn new(module: &'a Module) -> Self {
        Self { e: TextEmitter::new(module) }
    }

    fn finish(self) -> String {
        self.e.finish()
    }

    fn emit_preamble(&mut self) {
        let ns = sanitize_ident(&self.e.module.name, "module");
        self.e.wln("// Generated by jaw. Do not edit.");
        self.e.wln("#pragma once");
        self.e.wln("#include <cstdint>");
        self.e.wln("#include <vector>");
        self.e.wln("#include <array>");
        self.e.wln("#include <variant>");
        self.e.wln("#include <span>");
        self.e.wln("");
        self.e.wln("// Reader/Writer requirements:");
        self.e.wln("// bool write_raw(T const&)");
        self.e.wln("// bool  read_raw(T&)");
        self.e.wln("// C++20 required (std::span, std::variant). Endianness left to Reader/Writer.");
        self.e.wln("");
        self.e.wln(&format!("namespace {} {{", ns));
        self.e.indent();
        self.e.wln("namespace detail {");
        self.e.indent();
        self.e.wln("template <typename Reader, typename T> inline bool read_raw(Reader& r, T& v) { return r.read_raw(v); }");
        self.e.wln("");
        self.e.wln("template <typename Writer, typename T> inline bool write_raw(Writer& w, T const& v) { return w.write_raw(v); }");
        self.e.wln("");
        self.e.wln("template <typename Reader> inline bool borrow_bytes(Reader& r, size_t n, std::span<const std::byte>& out) { return r.borrow_bytes(n, out); }");
        self.e.wln("template <typename Reader, typename T> inline bool borrow_span(Reader& r, size_t n, std::span<const T>& out) {");
        self.e.indent();
        self.e.wln("std::span<const std::byte> bytes;");
        self.e.wln("if (!borrow_bytes(r, n * sizeof(T), bytes)) return false;");
        self.e.wln("out = std::span<const T>(reinterpret_cast<const T*>(bytes.data()), n);");
        self.e.wln("return true;");
        self.e.dedent();
        self.e.wln("}");
        self.e.dedent();
        self.e.wln("} // namespace detail");
        self.e.wln("");
    }

    fn emit_all_types(&mut self) {
        // Generate type declarations and read/write functions in topological order.
        // Only generate concrete definitions for named, user-defined types (skip builtins and anonymous inline types).
        let order: Vec<TypeID> = self.e.module.type_order.clone();
        for tid in order.into_iter() {
            let Some(ty) = self.e.module.lookup(tid) else {
                continue;
            };
            let Some(name_owned) = self.e.name_of(tid).map(|x| x.to_string()) else {
                continue;
            };
            // Skip builtins: defined_at == None
            if let Span::Builtin = ty.defined_at {
                continue;
            }

            match &ty.kind {
                TypeKind::Enum(e) => self.emit_enum(&name_owned, e),
                TypeKind::Bitfld(b) => self.emit_bitfield(&name_owned, b),
                TypeKind::Pack(p) => {
                    self.emit_pack(&name_owned, p);
                }
                TypeKind::Sequence(s) => {
                    self.emit_sequence_type(&name_owned, s);
                    self.emit_sequence_view(&name_owned, s);
                }
                TypeKind::Variant(v) => self.emit_variant(&name_owned, v),
                TypeKind::Alias(inner) => self.emit_alias(&name_owned, inner),
                TypeKind::Primitive(_) | TypeKind::Void => { /* already skipped by defined_at or no-op */ }
                TypeKind::DynamicArray(_) | TypeKind::FixedArray(_) => {
                    // Do not emit top-level for anonymous arrays; arrays should not be named top-level here.
                }
            }
            self.e.wln("");
            // Readers and Writers
            self.emit_read_fn(tid, &name_owned);
            self.emit_write_fn(tid, &name_owned);
            if matches!(ty.kind, TypeKind::Sequence(_) | TypeKind::Variant(_)) {
                self.emit_read_fn_view(tid, &name_owned);
                self.emit_write_fn_view(tid, &name_owned);
            }
            self.e.wln("");
        }

        // close namespaces
        self.e.dedent();
        let ns = sanitize_ident(&self.e.module.name, "module");
        self.e.wln(&format!("}} // namespace {}", ns));
    }

    fn emit_enum(&mut self, name: &str, e: &Enum) {
        let underlying = self.cpp_primitive(&e.ty);
        self.e.wln(&format!("enum class {} : {} {{", name, underlying));
        self.e.indent();
        for (mname, val) in e.members.iter() {
            self.e.wln(&format!("{} = {},", mname, val));
        }
        if let Some((dname, dval)) = &e.default {
            self.e.wln(&format!("{} = {},", dname, dval));
        }
        self.e.dedent();
        self.e.wln("};");
    }

    fn emit_bitfield(&mut self, name: &str, b: &Bitfld) {
        let underlying_tid = b.ty;
        let underlying_cpp = self.cpp_type_owned(underlying_tid);
        self.e.wln(&format!("struct {} {{", name));
        self.e.indent();
        self.e.wln(&format!("{} value{{}};", underlying_cpp));
        // Getters and setters
        for (fname, fty, range) in &b.members {
            let width = range.end() - range.start() + 1;
            let shift = range.start();
            let mask_val: u128 = if width >= 128 {
                u128::MAX
            } else {
                (1u128 << width) - 1
            };
            let mut mask_lit = String::new();
            if width >= 64 {
                // emit as 128 then cast
                write!(mask_lit, "{}ULL", mask_val as u64).unwrap();
            } else {
                // up to 63 bits safe in 64-bit literal
                write!(mask_lit, "{}ULL", (mask_val as u64)).unwrap();
            }
            let ret_ty = self.cpp_type_owned(*fty);
            self.e.wln(&format!(
                "inline {} get_{}() const {{ return static_cast<{}>((value >> {}) & ({})); }}",
                ret_ty, fname, ret_ty, shift, mask_lit
            ));
            self.e.wln(&format!(
                "inline void set_{}({} v) {{ value = static_cast<{}>((value & ~(({}) << {})) | ((static_cast<{}>(v) & ({})) << {})); }}",
                fname,
                ret_ty,
                underlying_cpp,
                mask_lit,
                shift,
                underlying_cpp,
                mask_lit,
                shift
            ));
        }
        self.e.dedent();
        self.e.wln("};");
    }

    fn emit_pack(&mut self, name: &str, p: &Pack) {
        self.e.wln(&format!("struct {} {{", name));
        self.e.indent();
        for (mname, mtid) in &p.members {
            let t = self.cpp_type_owned(*mtid);
            self.e.wln(&format!("{} {};", t, mname));
        }
        self.e.dedent();
        self.e.wln("};");
    }

    fn emit_sequence_type(&mut self, name: &str, s: &Sequence) {
        self.e.wln(&format!("struct {} {{", name));
        self.e.indent();
        for (mname, mtid) in &s.members {
            let t = self.cpp_type_owned(*mtid);
            self.e.wln(&format!("{} {};", t, mname));
        }
        self.e.dedent();
        self.e.wln("};");
    }

    fn emit_sequence_view(&mut self, name: &str, s: &Sequence) {
        let vname = format!("{}View", name);
        self.e.wln(&format!("struct {} {{", vname));
        self.e.indent();
        for (mname, mtid) in &s.members {
            let t = self.cpp_type_view_field(*mtid);
            self.e.wln(&format!("{} {};", t, mname));
        }
        self.e.dedent();
        self.e.wln("};");
    }

    fn emit_variant(&mut self, name: &str, v: &Variant) {
        //let discr_ty = self.cpp_type_owned(v.ty);
        // collect alternative types in declaration order
        let mut alt_types: Vec<String> = Vec::new();
        let mut alt_ref_types: Vec<String> = Vec::new();
        for (_, tid) in &v.members {
            let t = self.e.module.lookup(*tid).expect("unknown type");
            match &t.kind {
                TypeKind::Primitive(_) | TypeKind::Enum(_) | TypeKind::Bitfld(_) | TypeKind::Pack(_) | TypeKind::Sequence(_) | TypeKind::Variant(_) | TypeKind::DynamicArray(_) | TypeKind::FixedArray(_) | TypeKind::Alias(_) => {
                    let mut r = self.cpp_type_owned(*tid);
                    alt_types.push(r.clone());
                    r.push_str(" const* ");
                    alt_ref_types.push(r);
                }
                TypeKind::Void => {
                    alt_types.push("std::monostate".to_string());
                    alt_ref_types.push("std::monostate".to_string());
                }
            }
        }
        if let Some((_, dftid)) = &v.default {
            let t = self.e.module.lookup(*dftid).expect("unknown type");
            match &t.kind {
                TypeKind::Void => {
                    alt_types.push("std::monostate".to_string());
                    alt_ref_types.push("std::monostate".to_string());
                }
                _ => {
                    let mut r = self.cpp_type_owned(*dftid);
                    alt_types.push(r.clone());
                    r.push_str(" const* ");
                    alt_ref_types.push(r);
                }
            }
        }
        let alts = if alt_types.is_empty() {
            String::from("std::monostate")
        } else {
            alt_types.join(", ")
        };

        let alt_refs = if alt_ref_types.is_empty() {
            String::from("std::monostate")
        } else {
            alt_ref_types.join(", ")
        };

        self.e.wln(&format!(
            "struct {} {{ std::variant<{}> value; }};",
            name, alts
        ));

        self.e.wln(&format!(
            "struct {}View {{ std::variant<{}> value; }};",
            name, alt_refs
        ));
    }

    fn emit_alias(&mut self, name: &str, inner: &Type) {
        // Treat alias as using-declaration in C++
        let ty = self.cpp_type_from_type(inner);
        self.e.wln(&format!("using {} = {};", name, ty));
    }

    fn emit_read_fn(&mut self, tid: TypeID, name: &str) {
        // Definition
        self.e.wln(&format!(
            "template <typename Reader> inline bool read(Reader& r, {}& out) {{",
            name
        ));
        self.e.indent();
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Enum(e) => {
                let u = self.cpp_primitive(&e.ty);
                self.e.wln(&format!("{} tmp{{}};", u));
                self.e.wln("if (!detail::read_raw(r, tmp)) return false;");

                if let Some(def) = &e.default {
                    // slow mode
                    self.e.wln("switch (tmp) {");
                    self.e.indent();

                    for mem in &e.members {
                        self.e.wln(&format!("case {} : out = {name}::{}; break;", mem.1, mem.0));
                    }

                    self.e.wln(&format!("default: out = {name}::{};", def.0));
                    self.e.dedent();
                    self.e.wln("}");
                } else {
                    //fast mode
                    self.e.wln(&format!("out = static_cast<{name}>(tmp);"));
                }

                self.e.wln("return true;");
            }
            TypeKind::Bitfld(b) => {
                let u = self.cpp_type_owned(b.ty);
                self.e.wln(&format!("{} tmp{{}};", u));
                self.e.wln("if (!detail::read_raw(r, tmp)) return false;");
                self.e.wln("out.value = tmp;");
                self.e.wln("return true;");
            }
            TypeKind::Pack(_) => {
                self.e.wln("return r.read_raw(out);");
            }
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    self.emit_read_member(*mtid, &format!("out.{}", mname));
                }
                self.e.wln("return true;");
            }
            TypeKind::Variant(v) => {
                let discr_ty = self.cpp_primitive(&v.ty);
                self.e.wln(&format!("{} tag{{}};", discr_ty));
                self.e.wln("if (!detail::read_raw(r, tag)) return false;");
                self.e.wln("switch (static_cast<decltype(tag)>(tag)) {");
                self.e.indent();
                for (idx, (val, vt)) in v.members.iter().enumerate() {
                    self.e.wln(&format!("case {}: {{", val));
                    self.e.indent();
                    let t = self.e.module.lookup(*vt).unwrap();
                    match &t.kind {
                        TypeKind::Void => {
                            self.e.wln(&format!("(void)out.value.emplace<{}>();", idx));
                            self.e.wln("return true;");
                        }
                        _ => {
                            let val_cpp = self.cpp_type_owned(*vt);
                            self.e.wln(&format!("{}& tmp = out.value.emplace<{}>();", val_cpp, idx));
                            self.emit_read_member(*vt, "tmp");
                            self.e.wln("return true;");
                        }
                    }
                    self.e.dedent();
                    self.e.wln("}");
                }
                if let Some((_, dftid)) = &v.default {
                    let default_index = v.members.len();
                    self.e.wln("default: {");
                    self.e.indent();
                    let t = self.e.module.lookup(*dftid).unwrap();
                    match &t.kind {
                        TypeKind::Void => {
                            self.e.wln(&format!("(void)out.value.emplace<{}>();", default_index));
                            self.e.wln("return true;");
                        }
                        _ => {
                            let val_cpp = self.cpp_type_owned(*dftid);
                            self.e.wln(&format!(
                                "{}& tmp = out.value.emplace<{}>();",
                                val_cpp, default_index
                            ));
                            self.emit_read_member(*dftid, "tmp");
                            self.e.wln("return true;");
                        }
                    }
                    self.e.dedent();
                    self.e.wln("}");
                } else {
                    self.e.wln("default: return false;");
                }
                self.e.dedent();
                self.e.wln("}");
                self.e.wln("return true;");
            }
            _ => {
                // Arrays should not be top-level named; primitives are excluded.
                self.e.wln("return false;");
            }
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_write_fn(&mut self, tid: TypeID, name: &str) {
        self.e.wln(&format!(
            "template <typename Writer> inline bool write(Writer& w, const {}& in) {{",
            name
        ));
        self.e.indent();
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Enum(e) => {
                let u = self.cpp_primitive(&e.ty);
                self.e.wln(&format!("{} tmp = static_cast<{}>(in);", u, u));
                self.e.wln("return detail::write_raw(w, tmp);");
            }
            TypeKind::Bitfld(_) => {
                self.e.wln("return detail::write_raw(w, in.value);");
            }
            TypeKind::Pack(_) => {
                self.e.wln("return w.write_raw(in);");
            }
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    self.emit_write_member(*mtid, &format!("in.{}", mname));
                }
                self.e.wln("return true;");
            }
            TypeKind::Variant(v) => {
                // Write tag then payload matching active alternative (map index -> discriminant)
                let ty = self.cpp_primitive(&v.ty);
                self.e.wln("size_t __idx = in.value.index();");
                self.e.wln(&format!("{} tag{{}};", ty));
                self.e.wln("switch (__idx) {");
                self.e.indent();
                for (idx, (val, _vt)) in v.members.iter().enumerate() {
                    self.e.wln(&format!("case {}: tag = static_cast<{}>({}); break;", idx, ty, val));
                }
                if let Some((dfval, _)) = &v.default {
                    let default_index = v.members.len();
                    self.e.wln(&format!(
                        "case {}: tag = static_cast<{}>({}); break;",
                        default_index, ty, dfval
                    ));
                }
                self.e.wln("default: return false;");
                self.e.dedent();
                self.e.wln("}");
                self.e.wln("if (!detail::write_raw(w, tag)) return false;");
                self.e.wln("switch (__idx) {");
                self.e.indent();
                for (idx, (_val, vt)) in v.members.iter().enumerate() {
                    self.e.wln(&format!("case {}: {{", idx));
                    self.e.indent();
                    let t = self.e.module.lookup(*vt).unwrap();
                    match &t.kind {
                        TypeKind::Void => {
                            self.e.wln("return true;");
                        }
                        _ => {
                            self.e.wln(&format!("const auto& ptr = std::get<{}>(in.value);", idx));
                            self.emit_write_member(*vt, "ptr");
                            self.e.wln("return true;");
                        }
                    }
                    self.e.dedent();
                    self.e.wln("}");
                }
                if let Some((_dfval, dftid)) = &v.default {
                    let default_index = v.members.len();
                    self.e.wln(&format!("case {}: {{", default_index));
                    self.e.indent();
                    let t = self.e.module.lookup(*dftid).unwrap();
                    match &t.kind {
                        TypeKind::Void => {
                            self.e.wln("return true;");
                        }
                        _ => {
                            self.e.wln(&format!("const auto& ptr = std::get<{}>(in.value);", default_index));
                            self.emit_write_member(*dftid, "ptr");
                            self.e.wln("return true;");
                        }
                    }
                    self.e.dedent();
                    self.e.wln("}");
                }
                self.e.wln("default: return false;");
                self.e.dedent();
                self.e.wln("}");
                self.e.wln("return true;");
            }
            _ => {
                self.e.wln("return false;");
            }
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_write_fn_view(&mut self, tid: TypeID, name: &str) {
        let vname = format!("{}View", name);
        self.e.wln(&format!(
            "template <typename Writer> inline bool write(Writer& w, const {}& in) {{",
            vname
        ));
        self.e.indent();
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    self.emit_write_member(*mtid, &format!("in.{}", mname));
                }
                self.e.wln("return true;");
            }
            TypeKind::Variant(v) => {
                // Write tag then payload matching active alternative (view: pointers)
                let ty = self.cpp_primitive(&v.ty);
                self.e.wln("size_t __idx = in.value.index();");
                self.e.wln(&format!("{} tag{{}};", ty));
                self.e.wln("switch (__idx) {");
                self.e.indent();
                for (idx, (val, _vt)) in v.members.iter().enumerate() {
                    self.e.wln(&format!("case {}: tag = static_cast<{}>({}); break;", idx, ty, val));
                }
                if let Some((dfval, _)) = &v.default {
                    let default_index = v.members.len();
                    self.e.wln(&format!(
                        "case {}: tag = static_cast<{}>({}); break;",
                        default_index, ty, dfval
                    ));
                }
                self.e.wln("default: return false;");
                self.e.dedent();
                self.e.wln("}");
                self.e.wln("if (!detail::write_raw(w, tag)) return false;");
                self.e.wln("switch (__idx) {");
                self.e.indent();
                for (idx, (_val, vt)) in v.members.iter().enumerate() {
                    self.e.wln(&format!("case {}: {{", idx));
                    self.e.indent();
                    let t = self.e.module.lookup(*vt).unwrap();
                    match &t.kind {
                        TypeKind::Void => {
                            self.e.wln("return true;");
                        }
                        _ => {
                            self.e.wln(&format!("auto ptr = std::get<{}>(in.value);", idx));
                            self.emit_write_member(*vt, "*ptr");
                            self.e.wln("return true;");
                        }
                    }
                    self.e.dedent();
                    self.e.wln("}");
                }
                if let Some((_dfval, dftid)) = &v.default {
                    let default_index = v.members.len();
                    self.e.wln(&format!("case {}: {{", default_index));
                    self.e.indent();
                    let t = self.e.module.lookup(*dftid).unwrap();
                    match &t.kind {
                        TypeKind::Void => {
                            self.e.wln("return true;");
                        }
                        _ => {
                            self.e.wln(&format!("auto ptr = std::get<{}>(in.value);", default_index));
                            self.emit_write_member(*dftid, "*ptr");
                            self.e.wln("return true;");
                        }
                    }
                    self.e.dedent();
                    self.e.wln("}");
                }
                self.e.wln("default: return false;");
                self.e.dedent();
                self.e.wln("}");
                self.e.wln("return true;");
            }
            _ => {
                self.e.wln("return false;");
            }
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_read_fn_view(&mut self, tid: TypeID, name: &str) {
        let vname = format!("{}View", name);
        self.e.wln(&format!(
            "template <typename Reader> inline bool read(Reader& r, {}& out) {{",
            vname
        ));
        self.e.indent();
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    let field = format!("out.{}", mname);
                    let mty = self.e.module.lookup(*mtid).unwrap();
                    match &mty.kind {
                        TypeKind::Primitive(_p) => {
                            self.e.wln(&format!("if (!detail::read_raw(r, {})) return false;", field));
                        }
                        TypeKind::DynamicArray(ArrayKind::Dynamic { size_type, value_type }) => {
                            // zero-copy only for u8
                            let vty = self.e.module.lookup(*value_type).unwrap();
                            match &vty.kind {
                                TypeKind::Primitive(Primitive::U8) => {
                                    let st = self.e.module.lookup(*size_type).unwrap();
                                    let scpp = match &st.kind { TypeKind::Primitive(p) => self.cpp_primitive(p), _ => "size_t".into() };
                                    self.e.wln("{");
                                    self.e.indent();
                                    self.e.wln(&format!("{} __n{{}};", scpp));
                                    self.e.wln("if (!detail::read_raw(r, __n)) return false;");
                                    self.e.wln("std::span<const uint8_t> __span;");
                                    self.e.wln("if (!detail::borrow_span<uint8_t>(r, static_cast<size_t>(__n), __span)) return false;");
                                    self.e.wln(&format!("{} = __span;", field));
                                    self.e.dedent();
                                    self.e.wln("}");
                                }
                                _ => {
                                    self.e.wln("return false; // unsupported view read for non-u8 array");
                                }
                            }
                        }
                        TypeKind::FixedArray(ArrayKind::Fixed { count, value_type }) => {
                            let vty = self.e.module.lookup(*value_type).unwrap();
                            match &vty.kind {
                                TypeKind::Primitive(Primitive::U8) => {
                                    self.e.wln("{");
                                    self.e.indent();
                                    self.e.wln("std::span<const uint8_t> __span;");
                                    self.e.wln(&format!(
                                        "if (!detail::borrow_span<uint8_t>(r, {}, __span)) return false;",
                                        count
                                    ));
                                    self.e.wln(&format!(
                                        "{} = std::span<const uint8_t, {}>(__span.data(), {});",
                                        field, count, count
                                    ));
                                    self.e.dedent();
                                    self.e.wln("}");
                                }
                                _ => {
                                    self.e.wln("return false; // unsupported view read for non-u8 fixed array");
                                }
                            }
                        }
                        _ => {
                            self.e.wln("return false; // unsupported composite in SequenceView read");
                        }
                    }
                }
                self.e.wln("return true;");
            }
            TypeKind::Variant(_v) => {
                // Not supported generically: cannot create references to nested composites from stream
                self.e.wln("(void)r; (void)out; return false;");
            }
            _ => {
                self.e.wln("return false;");
            }
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_read_member(&mut self, tid: TypeID, lhs: &str) {
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(_p) => {
                self.e.wln(&format!("if (!detail::read_raw(r, {})) return false;", lhs));
            }
            TypeKind::Void => {
                self.e.wln("/* void: nothing to read */");
            }
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if self.e.name_of(tid).is_some() {
                    self.e.wln(&format!("if (!read(r, {})) return false;", lhs));
                } else {
                    // Anonymous composite, should not occur except arrays; fallback false
                    self.e.wln("return false;");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            }) => {
                // read size then elements
                self.e.wln("{");
                {
                    self.e.indent();
                    let size_cpp = self.cpp_type_owned(*size_type);
                    self.e.wln(&format!("{} __n{{}};", size_cpp));
                    self.e.wln("if (!detail::read_raw(r, __n)) return false;");
                    self.e.wln(&format!(
                        "{}.clear(); {}.resize(static_cast<size_t>(__n));",
                        lhs, lhs
                    ));
                    self.e.wln("for (size_t i = 0; i < static_cast<size_t>(__n); ++i) {");
                    self.e.indent();
                    let elem_lhs = format!("{}[i]", lhs);
                    self.emit_read_member(*value_type, &elem_lhs);
                    self.e.dedent();
                    self.e.wln("}");
                    self.e.dedent();
                }
                self.e.wln("}");
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                self.e.wln(&format!("for (size_t i = 0; i < {}; ++i) {{", count));
                self.e.indent();
                let elem_lhs = format!("{}[i]", lhs);
                self.emit_read_member(*value_type, &elem_lhs);
                self.e.dedent();
                self.e.wln("}");
            }
            TypeKind::Alias(inner) => {
                // read inner form directly
                let tmp_tid = tid; // not used distinctively here
                let _ = tmp_tid;
                // Fallback: not expected until alias parsing is implemented
                let inner_ty = self.cpp_type_from_type(inner);
                self.e.wln(&format!(
                    "// alias fallback; reading as inner type {};\n(void)sizeof({});",
                    inner_ty, inner_ty
                ));
                self.e.wln("return false;");
            }
        }
    }

    fn emit_write_member(&mut self, tid: TypeID, expr: &str) {
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(_) => {
                // rely on overload resolution via expr type
                self.e.wln(&format!(
                    "if (!detail::write_raw(w, {})) return false;",
                    expr
                ));
            }
            TypeKind::Void => {
                self.e.wln("/* void: nothing to write */");
            }
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if self.e.name_of(tid).is_some() {
                    self.e.wln(&format!("if (!write(w, {})) return false;", expr));
                } else {
                    self.e.wln("return false;");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            }) => {
                self.e.wln("{");
                self.e.indent();
                {
                    // write size then elements
                    let size_cpp = self.cpp_type_owned(*size_type);
                    self.e.wln(&format!(
                        "{} __n = static_cast<{}>({}.size());",
                        size_cpp, size_cpp, expr
                    ));
                    self.e.wln("if (!detail::write_raw(w, __n)) return false;");
                    self.e.wln(&format!("for (size_t i = 0; i < {}.size(); ++i) {{", expr));
                    self.e.indent();
                    let elem_expr = format!("{}[i]", expr);
                    self.emit_write_member(*value_type, &elem_expr);
                    self.e.dedent();
                    self.e.wln("}");
                }
                self.e.dedent();
                self.e.wln("}");
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                self.e.wln(&format!("for (size_t i = 0; i < {}; ++i) {{", count));
                self.e.indent();
                let elem_expr = format!("{}[i]", expr);
                self.emit_write_member(*value_type, &elem_expr);
                self.e.dedent();
                self.e.wln("}");
            }
            TypeKind::Alias(inner) => {
                let inner_ty = self.cpp_type_from_type(inner);
                self.e.wln(&format!(
                    "// alias fallback; writing as inner type {};\n(void)sizeof({});",
                    inner_ty, inner_ty
                ));
                self.e.wln("return false;");
            }
        }
    }

    fn cpp_primitive(&self, p: &Primitive) -> String {
        match p {
            Primitive::U8 => "uint8_t".into(),
            Primitive::U16 => "uint16_t".into(),
            Primitive::U32 => "uint32_t".into(),
            Primitive::U64 => "uint64_t".into(),
            Primitive::I8 => "int8_t".into(),
            Primitive::I16 => "int16_t".into(),
            Primitive::I32 => "int32_t".into(),
            Primitive::I64 => "int64_t".into(),
            Primitive::F32 => "float".into(),
            Primitive::F64 => "double".into(),
        }
    }

    fn cpp_type_owned(&self, tid: TypeID) -> String {
        let ty = self.e.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.cpp_primitive(p),
            TypeKind::Void => "std::monostate".to_string(),
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    name.to_string()
                } else {
                    // anonymous composite should not be referenced directly; fallback
                    "/*anon*/int".to_string()
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::vector<{}>", elem)
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::array<{}, {}>", elem, count)
            }
            TypeKind::Alias(inner) => self.cpp_type_from_type(inner),
        }
    }

    fn cpp_type_from_type(&self, ty: &Type) -> String {
        match &ty.kind {
            TypeKind::Primitive(p) => self.cpp_primitive(p),
            TypeKind::Void => "std::monostate".to_string(),
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                // cannot get TypeID from Type directly to find its name; used only for alias right now
                "/*alias_target*/int".to_string()
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::vector<{}>", elem)
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::array<{}, {}>", elem, count)
            }
            TypeKind::Alias(inner) => self.cpp_type_from_type(inner),
        }
    }

    fn cpp_type_view_field(&self, tid: TypeID) -> String {
        let ty = self.e.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.cpp_primitive(p),
            TypeKind::Void => "std::monostate".to_string(),
            TypeKind::Enum(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    name.to_string()
                } else {
                    "int".to_string()
                }
            }
            TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    format!("const {}&", name)
                } else {
                    "/*anon_ref*/int".to_string()
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::span<const {}>", elem)
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::span<const {}, {}>", elem, count)
            }
            TypeKind::Alias(inner) => {
                let base = self.cpp_type_from_type(inner);
                format!("const {}&", base)
            }
        }
    }
}
