use std::collections::HashMap;

use anyhow::{Result, anyhow, bail};

use crate::compile::{
    BitWidth, Datatype, Primitive, Signedness, Type, TypeID, TypeKind, VariantMember, World,
};

use super::*;

/// Emits a Python module for the given compiled `World`.
pub fn emit(world: &World, global: &GlobalOptions, out: &mut Outfile) -> Result<()> {
    let ctx = PythonContext::new(world, global)?;

    emit_preamble(&ctx, out);
    out.newline();

    for (id, ty) in ctx.types() {
        emit_type_definition(&ctx, out, id, ty)?;
    }

    for (id, ty) in ctx.types() {
        emit_read_impl(&ctx, out, id, ty)?;
        emit_write_impl(&ctx, out, id, ty)?;
    }

    Ok(())
}

struct PythonContext<'a> {
    world: &'a World,
    options: &'a GlobalOptions,
    names: HashMap<TypeID, String>,
}

impl<'a> PythonContext<'a> {
    /// Builds a codegen context (name mapping and options).
    fn new(world: &'a World, options: &'a GlobalOptions) -> Result<Self> {
        let mut names = HashMap::new();
        for (id, ty) in world.iter() {
            names.insert(id, sanitize(ty.ident.to_string()));
        }
        Ok(Self {
            world,
            options,
            names,
        })
    }

    /// Returns the generated Python identifier for a `TypeID`.
    fn name_of(&self, id: TypeID) -> String {
        self.names
            .get(&id)
            .expect("missing generated name for type id")
            .clone()
    }

    /// Iterates types in dependency order.
    fn types(&'a self) -> impl Iterator<Item = (TypeID, &'a Type)> + 'a {
        self.world.iter()
    }

    /// Resolves aliases transitively.
    fn resolve_alias(&self, id: TypeID) -> TypeID {
        let mut cur = id;
        loop {
            let ty = self.world.lookup(cur);
            match &ty.kind {
                TypeKind::Alias(a) => cur = a.other,
                _ => return cur,
            }
        }
    }

    /// Returns whether a `TypeID` corresponds to `void`.
    fn is_void(&self, id: TypeID) -> bool {
        matches!(self.world.lookup(id).kind, TypeKind::Void)
    }

    /// Returns the primitive for a type if it is directly primitive (after alias resolution).
    fn direct_primitive(&self, id: TypeID) -> Option<Primitive> {
        let resolved = self.resolve_alias(id);
        match self.world.lookup(resolved).kind {
            TypeKind::Primitive(p) => Some(p),
            _ => None,
        }
    }

    /// Returns the primitive for a type following aliases and enums, if any.
    fn underlying_primitive(&self, id: TypeID) -> Option<Primitive> {
        let ty = self.world.lookup(id);
        match &ty.kind {
            TypeKind::Primitive(p) => Some(*p),
            TypeKind::Alias(a) => self.underlying_primitive(a.other),
            TypeKind::Enum(e) => self.underlying_primitive(e.underlying),
            _ => None,
        }
    }

    /// Returns a PEP-484 type hint string for a `TypeID`.
    fn type_hint(&self, id: TypeID) -> Result<String> {
        let ty = self.world.lookup(id);
        let hint = match &ty.kind {
            TypeKind::Primitive(p) => match p.dtype {
                Datatype::Float => "float".to_string(),
                Datatype::Integer => "int".to_string(),
            },
            TypeKind::Void => "None".into(),
            TypeKind::Alias(alias) => return self.type_hint(alias.other),
            TypeKind::Pack(_) | TypeKind::Enum(_) | TypeKind::Bitfld(_) => self.name_of(id),
            TypeKind::Variant(_) => self.name_of(id),
            TypeKind::Sequence(_) => self.name_of(id),
            TypeKind::DynamicArray(arr) => {
                if let Some(_x) = self.direct_primitive(arr.value_type) {
                    // can we use x to constrain here?
                    "array.array".into()
                } else {
                    "list".into()
                }
            }
            TypeKind::FixedArray(arr) => {
                if self.direct_primitive(arr.value_type).is_some() {
                    "array.array".into()
                } else {
                    "list".into()
                }
            }
        };
        Ok(hint)
    }
}

/// Emits imports, runtime helpers, and shared read/write utilities.
fn emit_preamble<'a>(context: &PythonContext<'a>, out: &mut impl Sink) {
    out.wln("# Generated by jaw. Do not edit.");
    out.wln("from __future__ import annotations");
    out.wln("import array");
    out.wln("import enum");
    out.wln("import struct");
    out.wln("import sys");
    out.wln("from dataclasses import dataclass");
    out.wln("from typing import Iterable");
    out.wln("from typing import ClassVar");
    out.newline();

    out.wln("class Reader:");
    {
        let mut idt = out.indent();
        idt.wln("def __init__(self, data):");
        {
            let mut body = idt.indent();
            body.wln("self._buf = memoryview(data)");
            body.wln("self._pos = 0");
        }
        idt.wln("def _read_prim(self, fmt):");
        {
            let mut body = idt.indent();
            body.wln("size = struct.calcsize(fmt)");
            body.wln("end = self._pos + size");
            body.wln("if end > len(self._buf): raise EOFError('not enough data')");
            body.wln("(value,) = struct.unpack_from(fmt, self._buf, self._pos)");
            body.wln("self._pos = end");
            body.wln("return value");
        }
        idt.wln("def read_bytes(self, n):");
        {
            let mut body = idt.indent();
            body.wln("n = int(n)");
            body.wln("start = self._pos");
            body.wln("end = start + n");
            body.wln("if end > len(self._buf): raise EOFError('not enough data')");
            body.wln("self._pos = end");
            body.wln("return self._buf[start:end]");
        }
        for (method, fmt) in [
            ("read_u8", "<B"),
            ("read_i8", "<b"),
            ("read_u16", "<H"),
            ("read_i16", "<h"),
            ("read_u32", "<I"),
            ("read_i32", "<i"),
            ("read_u64", "<Q"),
            ("read_i64", "<q"),
            ("read_f32", "<f"),
            ("read_f64", "<d"),
        ] {
            idt.wln(&format!("def {method}(self):"));
            let mut body = idt.indent();
            body.wln(&format!("return self._read_prim('{fmt}')"));
        }
    }
    out.newline();

    out.wln("class Writer:");
    {
        let mut idt = out.indent();
        idt.wln("def __init__(self):");
        {
            let mut body = idt.indent();
            body.wln("self._out = bytearray()");
        }
        idt.wln("def getvalue(self):");
        {
            let mut body = idt.indent();
            body.wln("return bytes(self._out)");
        }
        idt.wln("def write_bytes(self, b):");
        {
            let mut body = idt.indent();
            body.wln("self._out.extend(b)");
        }
        idt.wln("def _write_prim(self, fmt, value):");
        {
            let mut body = idt.indent();
            body.wln("self._out.extend(struct.pack(fmt, value))");
        }
        for (method, fmt) in [
            ("write_u8", "<B"),
            ("write_i8", "<b"),
            ("write_u16", "<H"),
            ("write_i16", "<h"),
            ("write_u32", "<I"),
            ("write_i32", "<i"),
            ("write_u64", "<Q"),
            ("write_i64", "<q"),
            ("write_f32", "<f"),
            ("write_f64", "<d"),
        ] {
            idt.wln(&format!("def {method}(self, value):"));
            let mut body = idt.indent();
            body.wln(&format!("self._write_prim('{fmt}', value)"));
        }
    }
    out.newline();

    out.wln("def _read_primitive_array(reader, fmt, typecode, count):");
    {
        let mut idt = out.indent();
        idt.wln("count = int(count)");
        idt.wln("if count < 0: raise ValueError('negative array length')");
        idt.wln("size = struct.calcsize(fmt)");
        if let Some(guard_byte_size) = context.options.guard_array_size {
            idt.wln(&format!(
                "if (count * size) > {guard_byte_size}: raise ValueError('array too large')"
            ));
        }
        idt.wln("raw = reader.read_bytes(count * size)");
        idt.wln("arr = array.array(typecode)");
        idt.wln("arr.frombytes(raw)");
        idt.wln("if sys.byteorder != 'little' and arr.itemsize > 1: arr.byteswap()");
        idt.wln("return arr");
    }
    out.newline();
    out.wln("def _write_primitive_array(writer, fmt, typecode, values: Iterable):");
    {
        let mut idt = out.indent();
        idt.wln("if isinstance(values, array.array) and values.typecode == typecode:");
        {
            let mut body = idt.indent();
            body.wln("arr = values");
        }
        idt.wln("else:");
        {
            let mut body = idt.indent();
            body.wln("arr = array.array(typecode, values)");
        }
        idt.wln("if sys.byteorder != 'little' and arr.itemsize > 1:");
        {
            let mut body = idt.indent();
            body.wln("arr = arr[:]");
            body.wln("arr.byteswap()");
        }
        idt.wln("writer.write_bytes(arr.tobytes())");
    }
}

/// Emits Python type declarations (dataclasses, enums, and aliases).
fn emit_type_definition(
    ctx: &PythonContext,
    out: &mut impl Sink,
    id: TypeID,
    ty: &Type,
) -> Result<()> {
    let name = ctx.name_of(id);
    match &ty.kind {
        TypeKind::Alias(alias) => {
            let target_hint = ctx.type_hint(alias.other)?;
            out.wln(&format!("{name} = {target_hint}"));
            out.newline();
        }
        TypeKind::Enum(enm) => {
            out.wln("@enum.unique");
            out.wln(&format!("class {name}(enum.IntEnum):"));
            {
                let mut idt = out.indent();
                for m in &enm.members {
                    idt.wln(&format!("{} = {}", sanitize(&m.name), m.value));
                }
                if let Some(default) = &enm.default {
                    idt.wln(&format!("{} = {}", sanitize(&default.name), default.value));
                    idt.wln(&format!("__default__ = {}", sanitize(&default.name)));
                }
            }
            out.newline();
        }
        TypeKind::Bitfld(bitfld) => {
            out.wln("@dataclass");
            out.wln(&format!("class {name}:"));
            {
                let mut idt = out.indent();
                for m in &bitfld.members {
                    let hint = ctx.type_hint(m.underlying)?;
                    idt.wln(&format!("{}: {}", sanitize(&m.name), hint));
                }
            }
            out.newline();
        }
        TypeKind::Pack(pack) => {
            out.wln("@dataclass");
            out.wln(&format!("class {name}:"));
            {
                let mut idt = out.indent();
                for m in &pack.members {
                    let hint = ctx.type_hint(m.ty)?;
                    idt.wln(&format!("{}: {}", sanitize(&m.name), hint));
                }
            }
            out.newline();
        }
        TypeKind::Sequence(seq) => {
            out.wln("@dataclass");
            out.wln(&format!("class {name}:"));
            {
                let mut idt = out.indent();
                for m in &seq.members {
                    let hint = ctx.type_hint(m.ty)?;
                    idt.wln(&format!("{}: {}", sanitize(&m.name), hint));
                }
            }
            out.newline();
        }
        TypeKind::Variant(v) => {
            out.wln("@dataclass");
            out.wln(&format!("class {name}:"));
            {
                let mut idt = out.indent();
                idt.wln("tag: int = 0");
                idt.wln("value: object = None");

                for m in &v.members {
                    let mem_type_name = ctx.name_of(m.ty);
                    let case_name = variant_case_name(ctx, m);
                    idt.wln("@staticmethod");

                    if ctx.is_void(m.ty) {
                        idt.wln(&format!("def make_{0}():", case_name));
                    } else {
                        idt.wln(&format!(
                            "def make_{0}(value: {1}):",
                            case_name, mem_type_name
                        ));
                    }

                    {
                        let mut idt = idt.indent();
                        if ctx.is_void(m.ty) {
                            idt.wln(&format!("return {name}({}, None)", m.value));
                        } else {
                            idt.wln(&format!("return {name}({}, value)", m.value));
                        }
                    }
                }

                for m in &v.members {
                    let case_name = variant_case_name(ctx, m);

                    idt.wln(&format!("type_{}: ClassVar[int] = {}", case_name, m.value));

                    idt.wln(&format!("def is_{}(self):", case_name));
                    {
                        let mut idt = idt.indent();
                        idt.wln(&format!("return self.tag == self.type_{}", case_name));
                    }
                }
            }
            out.newline();
        }
        TypeKind::DynamicArray(_) | TypeKind::FixedArray(_) => {
            // Arrays are represented with built-in containers; no class emitted.
        }
        TypeKind::Primitive(_) | TypeKind::Void => {}
    }

    Ok(())
}

/// Emits Python `read_*` functions for a type.
fn emit_read_impl(ctx: &PythonContext, out: &mut impl Sink, id: TypeID, ty: &Type) -> Result<()> {
    let name = ctx.name_of(id);
    match &ty.kind {
        TypeKind::Alias(alias) => {
            out.wln(&format!("def read_{name}(reader):"));
            let mut idt = out.indent();
            idt.wln(&format!(
                "return {}",
                read_expr(ctx, alias.other, "reader")?
            ));
            idt.newline();
        }
        TypeKind::Pack(pack) => {
            out.wln(&format!("def read_{name}(reader):"));
            let mut idt = out.indent();
            idt.wln(&format!("return {name}("));
            {
                let mut args = idt.indent();
                for m in &pack.members {
                    let expr = read_expr(ctx, m.ty, "reader")?;
                    args.wln(&format!("{} = {},", sanitize(&m.name), expr));
                }
            }
            idt.wln(")");
            idt.newline();
        }
        TypeKind::Enum(enm) => {
            out.wln(&format!("def read_{name}(reader):"));
            let mut idt = out.indent();
            let base_read = read_primitive_method(ctx, enm.underlying)?;
            idt.wln(&format!("raw = reader.{base_read}()"));
            idt.wln(&format!("if raw in {name}._value2member_map_:"));
            {
                let mut body = idt.indent();
                body.wln(&format!("return {name}(raw)"));
            }
            if let Some(default) = &enm.default {
                idt.wln(&format!("return {name}.{}", sanitize(&default.name)));
            } else {
                idt.wln(&format!(
                    "raise ValueError(f'invalid discriminant for {name}: {{raw!r}}')"
                ));
            }
            idt.newline();
        }
        TypeKind::Bitfld(bitfld) => {
            out.wln(&format!("def read_{name}(reader):"));
            let mut idt = out.indent();
            let base_read = read_primitive_method(ctx, bitfld.underlying)?;
            idt.wln(&format!("raw = reader.{base_read}()"));
            for m in &bitfld.members {
                let start = m.range.start();
                let end = m.range.end();
                let width = end - start + 1;
                let mask = (1u128 << width) - 1;
                let field = sanitize(&m.name);
                let value_expr = format!("(raw >> {}) & 0x{:X}", start, mask);
                emit_bitfield_member_read(ctx, &mut idt, &field, m.underlying, &value_expr)?;
            }
            idt.wln(&format!("return {name}("));
            {
                let mut args = idt.indent();
                for m in &bitfld.members {
                    let field = sanitize(&m.name);
                    args.wln(&format!("{field} = {field},"));
                }
            }
            idt.wln(")");
            idt.newline();
        }
        TypeKind::Variant(variant) => {
            out.wln(&format!("def read_{name}(reader):"));
            let mut idt = out.indent();
            let disc_read = read_primitive_method(ctx, variant.discriminant)?;
            idt.wln(&format!("tag = reader.{disc_read}()"));
            for m in &variant.members {
                idt.wln(&format!("if tag == {}:", m.value));
                let mut body = idt.indent();
                if ctx.is_void(m.ty) {
                    body.wln(&format!("return {name}(tag=tag, value=None)"));
                } else {
                    let expr = read_expr(ctx, m.ty, "reader")?;
                    body.wln(&format!("val = {expr}"));
                    body.wln(&format!("return {name}(tag=tag, value=val)"));
                }
            }
            idt.wln(&format!(
                "raise ValueError(f'unknown tag for {name}: {{tag!r}}')"
            ));
            idt.newline();
        }
        TypeKind::Sequence(seq) => {
            out.wln(&format!("def read_{name}(reader):"));
            let mut idt = out.indent();
            idt.wln(&format!("return {name}("));
            {
                let mut args = idt.indent();
                for m in &seq.members {
                    let expr = read_expr(ctx, m.ty, "reader")?;
                    args.wln(&format!("{} = {},", sanitize(&m.name), expr));
                }
            }
            idt.wln(")");
            idt.newline();
        }
        TypeKind::DynamicArray(arr) => {
            out.wln(&format!("def read_{name}(reader):"));
            let mut idt = out.indent();
            let size_read = read_primitive_method(ctx, arr.size_type)?;
            idt.wln(&format!("count = reader.{size_read}()"));
            idt.wln("count = int(count)");
            idt.wln("if count < 0: raise ValueError('negative array length')");
            if let Some(guard_byte_size) = ctx.options.guard_array_size {
                idt.wln(&format!(
                    "if count > {guard_byte_size}: raise ValueError('array too large')"
                ));
            }
            if let Some(p) = ctx.direct_primitive(arr.value_type) {
                let fmt = map_primitive_fmt(p)?;
                let typecode = map_typecode(p)?;
                idt.wln(&format!(
                    "return _read_primitive_array(reader, '{fmt}', '{typecode}', count)"
                ));
            } else {
                idt.wln("out = []");
                idt.wln("for _ in range(int(count)):");
                {
                    let mut body = idt.indent();
                    let expr = read_expr(ctx, arr.value_type, "reader")?;
                    body.wln(&format!("out.append({expr})"));
                }
                idt.wln("return out");
            }
            idt.newline();
        }
        TypeKind::FixedArray(arr) => {
            out.wln(&format!("def read_{name}(reader):"));
            let mut idt = out.indent();
            if let Some(p) = ctx.direct_primitive(arr.value_type) {
                let fmt = map_primitive_fmt(p)?;
                let typecode = map_typecode(p)?;
                idt.wln(&format!(
                    "return _read_primitive_array(reader, '{fmt}', '{typecode}', {})",
                    arr.count
                ));
            } else {
                idt.wln("out = []");
                idt.wln(&format!("for _ in range({}):", arr.count));
                {
                    let mut body = idt.indent();
                    let expr = read_expr(ctx, arr.value_type, "reader")?;
                    body.wln(&format!("out.append({expr})"));
                }
                idt.wln("return out");
            }
            idt.newline();
        }
        TypeKind::Primitive(_) | TypeKind::Void => {}
    }

    Ok(())
}

/// Emits Python `write_*` functions for a type.
fn emit_write_impl(ctx: &PythonContext, out: &mut impl Sink, id: TypeID, ty: &Type) -> Result<()> {
    let name = ctx.name_of(id);
    match &ty.kind {
        TypeKind::Alias(alias) => {
            out.wln(&format!("def write_{name}(writer, value):"));
            let mut idt = out.indent();
            write_value(ctx, &mut idt, alias.other, "value")?;
            idt.newline();
        }
        TypeKind::Pack(pack) => {
            out.wln(&format!("def write_{name}(writer, value):"));
            let mut idt = out.indent();
            for m in &pack.members {
                write_value(ctx, &mut idt, m.ty, &format!("value.{}", sanitize(&m.name)))?;
            }
            idt.newline();
        }
        TypeKind::Enum(enm) => {
            out.wln(&format!("def write_{name}(writer, value):"));
            let mut idt = out.indent();
            let write_fn = write_primitive_method(ctx, enm.underlying)?;
            idt.wln(&format!("writer.{write_fn}(int(value))"));
            idt.newline();
        }
        TypeKind::Bitfld(bitfld) => {
            out.wln(&format!("def write_{name}(writer, value):"));
            let mut idt = out.indent();
            let write_fn = write_primitive_method(ctx, bitfld.underlying)?;
            idt.wln("raw = 0");
            for m in &bitfld.members {
                let start = m.range.start();
                let end = m.range.end();
                let width = end - start + 1;
                let mask = (1u128 << width) - 1;
                idt.wln(&format!(
                    "raw |= (int(value.{}) & 0x{:X}) << {}",
                    sanitize(&m.name),
                    mask,
                    start
                ));
            }
            idt.wln(&format!("writer.{write_fn}(raw)"));
            idt.newline();
        }
        TypeKind::Variant(variant) => {
            out.wln(&format!("def write_{name}(writer, value):"));
            let mut idt = out.indent();
            let write_tag = write_primitive_method(ctx, variant.discriminant)?;
            idt.wln(&format!("writer.{write_tag}(int(value.tag))"));
            for m in &variant.members {
                idt.wln(&format!("if int(value.tag) == {}:", m.value));
                let mut body = idt.indent();
                if ctx.is_void(m.ty) {
                    body.wln("return");
                } else {
                    write_value(ctx, &mut body, m.ty, "value.value")?;
                    body.wln("return");
                }
            }
            idt.wln(&format!(
                "raise ValueError(f'unknown tag for {name}: {{value.tag!r}}')"
            ));
            idt.newline();
        }
        TypeKind::Sequence(seq) => {
            out.wln(&format!("def write_{name}(writer, value):"));
            let mut idt = out.indent();
            for m in &seq.members {
                write_value(ctx, &mut idt, m.ty, &format!("value.{}", sanitize(&m.name)))?;
            }
            idt.newline();
        }
        TypeKind::DynamicArray(arr) => {
            out.wln(&format!("def write_{name}(writer, values):"));
            let mut idt = out.indent();
            let max_len = max_len_for_size(ctx, arr.size_type)?;
            idt.wln("# Fail instead of truncating if the list does not fit in the count type.");
            idt.wln(&format!(
                "if len(values) > {}: raise ValueError('array length too large to encode')",
                max_len
            ));
            let size_write = write_primitive_method(ctx, arr.size_type)?;
            idt.wln(&format!("writer.{size_write}(len(values))"));
            if let Some(p) = ctx.direct_primitive(arr.value_type) {
                let fmt = map_primitive_fmt(p)?;
                let typecode = map_typecode(p)?;
                idt.wln(&format!(
                    "_write_primitive_array(writer, '{fmt}', '{typecode}', values)"
                ));
            } else {
                idt.wln("for item in values:");
                let mut body = idt.indent();
                write_value(ctx, &mut body, arr.value_type, "item")?;
            }
            idt.newline();
        }
        TypeKind::FixedArray(arr) => {
            out.wln(&format!("def write_{name}(writer, values):"));
            let mut idt = out.indent();
            if let Some(p) = ctx.direct_primitive(arr.value_type) {
                let fmt = map_primitive_fmt(p)?;
                let typecode = map_typecode(p)?;
                idt.wln(&format!(
                    "if len(values) != {}: raise ValueError('expected {} items')",
                    arr.count, arr.count
                ));
                idt.wln(&format!(
                    "_write_primitive_array(writer, '{fmt}', '{typecode}', values)"
                ));
            } else {
                idt.wln(&format!(
                    "if len(values) != {}: raise ValueError('expected {} items')",
                    arr.count, arr.count
                ));
                idt.wln("for item in values:");
                let mut body = idt.indent();
                write_value(ctx, &mut body, arr.value_type, "item")?;
            }
            idt.newline();
        }
        TypeKind::Primitive(_) | TypeKind::Void => {}
    }
    Ok(())
}

/// Builds a Python expression string to read a value of `id` from `reader_ident`.
fn read_expr(ctx: &PythonContext, id: TypeID, reader_ident: &str) -> Result<String> {
    let ty = ctx.world.lookup(id);
    let expr = match &ty.kind {
        TypeKind::Primitive(p) => {
            let method = read_primitive_method_direct(*p)?;
            format!("{reader_ident}.{method}()")
        }
        TypeKind::Void => "None".into(),
        TypeKind::Alias(alias) => return read_expr(ctx, alias.other, reader_ident),
        _ => format!("read_{}({reader_ident})", ctx.name_of(id)),
    };
    Ok(expr)
}

/// Emits Python statements that write `value_expr` of type `id` into `writer`.
fn write_value(
    ctx: &PythonContext,
    out: &mut impl Sink,
    id: TypeID,
    value_expr: &str,
) -> Result<()> {
    let ty = ctx.world.lookup(id);
    match &ty.kind {
        TypeKind::Primitive(p) => {
            let method = write_primitive_method_direct(*p)?;
            out.wln(&format!("writer.{method}({})", value_expr));
        }
        TypeKind::Void => {
            // nothing to write
        }
        TypeKind::Alias(alias) => write_value(ctx, out, alias.other, value_expr)?,
        _ => {
            out.wln(&format!(
                "write_{}(writer, {})",
                ctx.name_of(id),
                value_expr
            ));
        }
    }
    Ok(())
}

/// Emits code to decode a single bitfield member into a local variable.
fn emit_bitfield_member_read(
    ctx: &PythonContext,
    out: &mut impl Sink,
    field_name: &str,
    ty_id: TypeID,
    value_expr: &str,
) -> Result<()> {
    let ty = ctx.world.lookup(ty_id);
    match &ty.kind {
        TypeKind::Primitive(_) => {
            out.wln(&format!("{field_name} = int({value_expr})"));
        }
        TypeKind::Alias(alias) => {
            emit_bitfield_member_read(ctx, out, field_name, alias.other, value_expr)?
        }
        TypeKind::Enum(enm) => {
            let enum_name = ctx.name_of(ty_id);
            out.wln(&format!("{field_name}_raw = int({value_expr})"));
            out.wln(&format!(
                "if {field_name}_raw in {enum_name}._value2member_map_:"
            ));
            {
                let mut body = out.indent();
                body.wln(&format!("{field_name} = {enum_name}({field_name}_raw)"));
            }
            if let Some(default) = &enm.default {
                out.wln("else:");
                let mut body = out.indent();
                body.wln(&format!(
                    "{field_name} = {enum_name}.{}",
                    sanitize(&default.name)
                ));
            } else {
                out.wln("else:");
                let mut body = out.indent();
                body.wln(&format!(
                    "raise ValueError(f'invalid discriminant for {enum_name} in bitfield: {{{field_name}_raw!r}}')"
                ));
            }
        }
        _ => bail!("unsupported bitfield member type"),
    }
    Ok(())
}

/// Computes a stable, unique variant case name.
fn variant_case_name(ctx: &PythonContext, m: &VariantMember) -> String {
    sanitize(format!("{}_{}", ctx.name_of(m.ty), m.value))
}

// Shared bound for dynamic array length encoding, based on the declared counter type.
/// Returns the maximum encodable array length for a given size-counter type.
fn max_len_for_size(ctx: &PythonContext, id: TypeID) -> Result<u128> {
    let prim = ctx
        .underlying_primitive(id)
        .ok_or_else(|| anyhow!("expected primitive-compatible type"))?;
    match (prim.dtype, prim.sign, prim.width) {
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W8) => Ok(u8::MAX as u128),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W16) => Ok(u16::MAX as u128),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W32) => Ok(u32::MAX as u128),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W64) => Ok(u64::MAX as u128),
        _ => bail!("array size type must be an unsigned integer"),
    }
}

/// Returns the reader method name for a primitive-compatible type.
fn read_primitive_method(ctx: &PythonContext, id: TypeID) -> Result<&'static str> {
    let p = ctx
        .underlying_primitive(id)
        .ok_or_else(|| anyhow!("expected primitive-compatible type"))?;
    read_primitive_method_direct(p)
}

/// Returns the writer method name for a primitive-compatible type.
fn write_primitive_method(ctx: &PythonContext, id: TypeID) -> Result<&'static str> {
    let p = ctx
        .underlying_primitive(id)
        .ok_or_else(|| anyhow!("expected primitive-compatible type"))?;
    write_primitive_method_direct(p)
}

/// Returns the reader method name for a specific primitive.
fn read_primitive_method_direct(p: Primitive) -> Result<&'static str> {
    match (p.dtype, p.sign, p.width) {
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W8) => Ok("read_u8"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W16) => Ok("read_u16"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W32) => Ok("read_u32"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W64) => Ok("read_u64"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W8) => Ok("read_i8"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W16) => Ok("read_i16"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W32) => Ok("read_i32"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W64) => Ok("read_i64"),
        (Datatype::Float, _, BitWidth::W32) => Ok("read_f32"),
        (Datatype::Float, _, BitWidth::W64) => Ok("read_f64"),
        _ => bail!("unsupported primitive type"),
    }
}

/// Returns the writer method name for a specific primitive.
fn write_primitive_method_direct(p: Primitive) -> Result<&'static str> {
    match (p.dtype, p.sign, p.width) {
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W8) => Ok("write_u8"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W16) => Ok("write_u16"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W32) => Ok("write_u32"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W64) => Ok("write_u64"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W8) => Ok("write_i8"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W16) => Ok("write_i16"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W32) => Ok("write_i32"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W64) => Ok("write_i64"),
        (Datatype::Float, _, BitWidth::W32) => Ok("write_f32"),
        (Datatype::Float, _, BitWidth::W64) => Ok("write_f64"),
        _ => bail!("unsupported primitive type"),
    }
}

/// Maps a primitive to a `struct` format string.
fn map_primitive_fmt(p: Primitive) -> Result<&'static str> {
    match (p.dtype, p.sign, p.width) {
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W8) => Ok("<B"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W16) => Ok("<H"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W32) => Ok("<I"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W64) => Ok("<Q"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W8) => Ok("<b"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W16) => Ok("<h"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W32) => Ok("<i"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W64) => Ok("<q"),
        (Datatype::Float, _, BitWidth::W32) => Ok("<f"),
        (Datatype::Float, _, BitWidth::W64) => Ok("<d"),
        _ => bail!("unsupported primitive type"),
    }
}

/// Maps a primitive to an `array.array` typecode.
fn map_typecode(p: Primitive) -> Result<&'static str> {
    match (p.dtype, p.sign, p.width) {
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W8) => Ok("B"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W16) => Ok("H"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W32) => Ok("I"),
        (Datatype::Integer, Signedness::Unsigned, BitWidth::W64) => Ok("Q"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W8) => Ok("b"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W16) => Ok("h"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W32) => Ok("i"),
        (Datatype::Integer, Signedness::Signed, BitWidth::W64) => Ok("q"),
        (Datatype::Float, _, BitWidth::W32) => Ok("f"),
        (Datatype::Float, _, BitWidth::W64) => Ok("d"),
        _ => bail!("unsupported primitive type"),
    }
}

/// Sanitizes DSL identifiers into valid Python identifiers.
fn sanitize<S: AsRef<str>>(s: S) -> String {
    let raw = s.as_ref();
    let mut out = String::with_capacity(raw.len());
    for (i, ch) in raw.chars().enumerate() {
        let valid = ch.is_ascii_alphanumeric() || ch == '_';
        if !valid {
            out.push('_');
            continue;
        }
        if i == 0 && ch.is_ascii_digit() {
            out.push('_');
        }
        out.push(ch);
    }
    if out.is_empty() { "_t".into() } else { out }
}
