//! Python backend: emits a single module using `ctypes` for POD structs
//! and ad-hoc Reader/Writer classes for I/O.
//!
//! The generated code mirrors the layout and read/write semantics of the
//! other backends to support the cross-language roundtrip tests.
use crate::{module::*, tokens::Span};
use crate::codegen::common::{TextEmitter, sanitize_ident};

/// Emit a Python module as a single string into the given writer.
pub fn emit_python(
    module: Module,
    mut file: impl std::io::Write,
) -> Result<(), super::GeneratorError> {
    let mut e = PyEmitter::new(&module);
    e.emit_preamble();
    e.emit_all_types();
    let string = e.finish();

    file.write_all(string.as_bytes())?;

    Ok(())
}

/// Implementation of the Python emitter backed by a `TextEmitter`.
struct PyEmitter<'a> { e: TextEmitter<'a> }

impl<'a> PyEmitter<'a> {
    fn new(module: &'a Module) -> Self {
        Self { e: TextEmitter::new(module) }
    }

    fn finish(self) -> String {
        self.e.finish()
    }

    fn emit_preamble(&mut self) {
        self.e.wln("# Generated by jaw. Do not edit.");
        self.e.wln("import ctypes");
        self.e.wln("import struct");
        self.e.wln("");
        self.e.wln("# Little-endian reader/writer for primitives and raw bytes");
        self.e.wln("class Reader:");
        self.e.indent();
        self.e.wln("def __init__(self, data):");
        self.e.indent();
        self.e.wln("self._buf = memoryview(data)");
        self.e.wln("self._pos = 0");
        self.e.dedent();
        self.e.wln("");
        // primitives
        for (name, fmt) in [
            ("u8", "<B"),
            ("i8", "<b"),
            ("u16", "<H"),
            ("i16", "<h"),
            ("u32", "<I"),
            ("i32", "<i"),
            ("u64", "<Q"),
            ("i64", "<q"),
            ("f32", "<f"),
            ("f64", "<d"),
        ] {
            self.e.wln(&format!("def read_{}(self):", name));
            self.e.indent();
            self.e.wln(&format!(
                "(v,) = struct.unpack_from(\"{}\", self._buf, self._pos)",
                fmt
            ));
            self.e.wln(&format!(
                "self._pos += {}",
                match name {
                    "u8" | "i8" => "1",
                    "u16" | "i16" => "2",
                    "u32" | "i32" | "f32" => "4",
                    "u64" | "i64" | "f64" => "8",
                    _ => "0",
                }
            ));
            self.e.wln("return v");
            self.e.dedent();
        }
        self.e.wln("def read_bytes(self, n):");
        self.e.indent();
        self.e.wln("start = self._pos");
        self.e.wln("end = start + int(n)");
        self.e.wln("if end > len(self._buf): raise EOFError('not enough data')");
        self.e.wln("self._pos = end");
        self.e.wln("return bytes(self._buf[start:end])");
        self.e.dedent();
        self.e.dedent();
        self.e.wln("");

        self.e.wln("class Writer:");
        self.e.indent();
        self.e.wln("def __init__(self):");
        self.e.indent();
        self.e.wln("self._out = bytearray()");
        self.e.dedent();
        self.e.wln("def getvalue(self): return bytes(self._out)");
        for (name, fmt) in [
            ("u8", "<B"),
            ("i8", "<b"),
            ("u16", "<H"),
            ("i16", "<h"),
            ("u32", "<I"),
            ("i32", "<i"),
            ("u64", "<Q"),
            ("i64", "<q"),
            ("f32", "<f"),
            ("f64", "<d"),
        ] {
            self.e.wln(&format!("def write_{}(self, v):", name));
            self.e.indent();
            self.e.wln(&format!("self._out.extend(struct.pack(\"{}\", v))", fmt));
            self.e.dedent();
        }
        self.e.wln("def write_bytes(self, b): self._out.extend(b)");
        self.e.wln("def write_raw(self, obj):");
        self.e.indent();
        self.e.wln("self._out.extend(ctypes.string_at(ctypes.addressof(obj), ctypes.sizeof(obj)))");
        self.e.dedent();
        self.e.dedent();
        self.e.wln("");
    }

    fn emit_all_types(&mut self) {
        let order: Vec<TypeID> = self.e.module.type_order.clone();
        for tid in order.into_iter() {
            let Some(ty) = self.e.module.lookup(tid) else {
                continue;
            };
            let Some(name_owned) = self.e.name_of(tid).map(|x| x.to_string()) else {
                continue;
            };
            if let Span::Builtin = ty.defined_at {
                continue;
            }

            match &ty.kind {
                TypeKind::Enum(e) => self.emit_enum(&name_owned, e),
                TypeKind::Bitfld(b) => self.emit_bitfield(&name_owned, b),
                TypeKind::Pack(p) => self.emit_pack(&name_owned, p),
                TypeKind::Sequence(s) => self.emit_sequence_type(&name_owned, s),
                TypeKind::Variant(v) => self.emit_variant_type(&name_owned, v),
                TypeKind::Alias(_) => { /* not implemented */ }
                TypeKind::Primitive(_) | TypeKind::DynamicArray(_) | TypeKind::FixedArray(_) => {}
            }
            self.e.wln("");
            self.emit_read_fn(tid, &name_owned);
            self.emit_write_fn(tid, &name_owned);
            self.e.wln("");
        }
    }

    fn py_ctype(&self, p: &Primitive) -> &'static str {
        match p {
            Primitive::U8 => "ctypes.c_uint8",
            Primitive::U16 => "ctypes.c_uint16",
            Primitive::U32 => "ctypes.c_uint32",
            Primitive::U64 => "ctypes.c_uint64",
            Primitive::I8 => "ctypes.c_int8",
            Primitive::I16 => "ctypes.c_int16",
            Primitive::I32 => "ctypes.c_int32",
            Primitive::I64 => "ctypes.c_int64",
            Primitive::F32 => "ctypes.c_float",
            Primitive::F64 => "ctypes.c_double",
        }
    }

    fn py_read_prim(&self, p: &Primitive) -> &'static str {
        match p {
            Primitive::U8 => "read_u8",
            Primitive::U16 => "read_u16",
            Primitive::U32 => "read_u32",
            Primitive::U64 => "read_u64",
            Primitive::I8 => "read_i8",
            Primitive::I16 => "read_i16",
            Primitive::I32 => "read_i32",
            Primitive::I64 => "read_i64",
            Primitive::F32 => "read_f32",
            Primitive::F64 => "read_f64",
        }
    }

    fn py_write_prim(&self, p: &Primitive) -> &'static str {
        match p {
            Primitive::U8 => "write_u8",
            Primitive::U16 => "write_u16",
            Primitive::U32 => "write_u32",
            Primitive::U64 => "write_u64",
            Primitive::I8 => "write_i8",
            Primitive::I16 => "write_i16",
            Primitive::I32 => "write_i32",
            Primitive::I64 => "write_i64",
            Primitive::F32 => "write_f32",
            Primitive::F64 => "write_f64",
        }
    }

    fn ctype_for_pack_field(&self, tid: TypeID) -> String {
        let ty = self.e.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.py_ctype(p).to_string(),
            TypeKind::Enum(e) => self.py_ctype(&e.ty).to_string(),
            TypeKind::Bitfld(_) | TypeKind::Pack(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    sanitize_ident(name, "T")
                } else {
                    "ctypes.c_int".to_string()
                }
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let elem = self.ctype_for_pack_field(*value_type);
                format!("({} * {})", elem, count)
            }
            // Non-POD not allowed in pack; provide fallback
            _ => "ctypes.c_int".to_string(),
        }
    }

    fn emit_enum(&mut self, name: &str, e: &Enum) {
        let cls = sanitize_ident(name, "T");
        self.e.wln(&format!("class {}:", cls));
        self.e.indent();
        if e.members.is_empty() && e.default.is_none() {
            self.e.wln("pass");
        } else {
            for (mname, val) in e.members.iter() {
                let n = sanitize_ident(mname, "T");
                self.e.wln(&format!("{} = {}", n, val));
            }
            if let Some((dname, dval)) = &e.default {
                let n = sanitize_ident(dname, "T");
                self.e.wln(&format!("{} = {}", n, dval));
                self.e.wln(&format!("__default__ = {}", dval));
            }
        }
        self.e.dedent();
    }

    fn emit_bitfield(&mut self, name: &str, b: &Bitfld) {
        let cls = sanitize_ident(name, "T");
        let underlying = self.e.module.lookup(b.ty).unwrap();
        let underlying_py = match &underlying.kind {
            TypeKind::Primitive(p) => self.py_ctype(p).to_string(),
            TypeKind::Enum(e) => self.py_ctype(&e.ty).to_string(),
            _ => "ctypes.c_uint32".to_string(),
        };
        self.e.wln(&format!("class {}(ctypes.Structure):", cls));
        self.e.indent();
        self.e.wln("_fields_ = [");
        self.e.indent();
        self.e.wln(&format!("('value', {}),", underlying_py));
        self.e.dedent();
        self.e.wln("]");
        // accessors
        for (fname, _fty, range) in &b.members {
            let width = range.end() - range.start() + 1;
            let shift = range.start();
            let mask_val: u128 = if width >= 128 {
                u128::MAX
            } else {
                (1u128 << width) - 1
            };
            self.e.wln(&format!("def get_{}(self):", sanitize_ident(fname, "T")));
            self.e.indent();
            self.e.wln(&format!(
                "return (int(self.value) >> {}) & {}",
                shift, mask_val
            ));
            self.e.dedent();
            self.e.wln(&format!("def set_{}(self, v):", sanitize_ident(fname, "T")));
            self.e.indent();
            self.e.wln(&format!(
                "self.value = (int(self.value) & ~(({}) << {})) | ((int(v) & {}) << {})",
                mask_val, shift, mask_val, shift
            ));
            self.e.dedent();
        }
        self.e.dedent();
    }

    fn emit_pack(&mut self, name: &str, p: &Pack) {
        let cls = sanitize_ident(name, "T");
        self.e.wln(&format!("class {}(ctypes.Structure):", cls));
        self.e.indent();
        self.e.wln("_fields_ = [");
        self.e.indent();
        for (mname, mtid) in &p.members {
            let t = self.ctype_for_pack_field(*mtid);
            self.e.wln(&format!("('{}', {}),", sanitize_ident(mname, "T"), t));
        }
        self.e.dedent();
        self.e.wln("]");
        self.e.dedent();
    }

    fn emit_sequence_type(&mut self, name: &str, s: &Sequence) {
        let cls = sanitize_ident(name, "T");
        self.e.wln(&format!("class {}:", cls));
        self.e.indent();
        self.e.wln("def __init__(self):");
        self.e.indent();
        if s.members.is_empty() {
            self.e.wln("pass");
        } else {
            for (mname, _mtid) in &s.members {
                self.e.wln(&format!("self.{} = None", sanitize_ident(mname, "T")));
            }
        }
        self.e.dedent();
        self.e.dedent();
    }

    fn emit_variant_type(&mut self, name: &str, _v: &Variant) {
        let cls = sanitize_ident(name, "T");
        self.e.wln(&format!("class {}:", cls));
        self.e.indent();
        self.e.wln("def __init__(self, tag=0, value=None):");
        self.e.indent();
        self.e.wln("self.tag = int(tag)");
        self.e.wln("self.value = value");
        self.e.dedent();
        self.e.dedent();
    }

    fn emit_read_fn(&mut self, tid: TypeID, name: &str) {
        let cls = sanitize_ident(name, "T");
        self.e.wln(&format!("def read_{}(r):", cls));
        self.e.indent();
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Enum(e) => {
                let readm = self.py_read_prim(&e.ty);
                self.e.wln(&format!("tmp = r.{}()", readm));
                if e.default.is_some() {
                    let mut cases: Vec<String> = Vec::new();
                    for (_n, v) in &e.members {
                        cases.push(v.to_string());
                    }
                    let dval = e.default.as_ref().unwrap().1;
                    self.e.wln(&format!(
                        "return tmp if tmp in {{{}}} else {}",
                        cases.join(", "),
                        dval
                    ));
                } else {
                    self.e.wln("return tmp");
                }
            }
            TypeKind::Bitfld(b) => {
                // read underlying then assign value
                let underlying = self.e.module.lookup(b.ty).unwrap();
                let prim = match &underlying.kind {
                    TypeKind::Primitive(p) => p,
                    TypeKind::Enum(e) => &e.ty,
                    _ => panic!("invalid bitfield base"),
                };
                let readm = self.py_read_prim(prim);
                self.e.wln(&format!("tmp = r.{}()", readm));
                self.e.wln(&format!("out = {}()", cls));
                self.e.wln("out.value = tmp");
                self.e.wln("return out");
            }
            TypeKind::Pack(_) => {
                self.e.wln(&format!("size = ctypes.sizeof({})", cls));
                self.e.wln("data = r.read_bytes(size)");
                self.e.wln(&format!("return {}.from_buffer_copy(data)", cls));
            }
            TypeKind::Sequence(s) => {
                self.e.wln(&format!("out = {}()", cls));
                for (mname, mtid) in &s.members {
                    let dest = format!("out.{}", sanitize_ident(mname, "T"));
                    self.emit_read_member(*mtid, &dest);
                }
                self.e.wln("return out");
            }
            TypeKind::Variant(v) => {
                let readm = self.py_read_prim(&v.ty);
                self.e.wln(&format!("tag = r.{}()", readm));
                // emit dispatch
                if !v.members.is_empty() {
                    self.e.wln("value = None");
                    self.e.wln("handled = False");
                    for (val, vt) in &v.members {
                        self.e.wln(&format!("if tag == {}:", val));
                        self.e.indent();
                        self.emit_read_member_assign(*vt, "value");
                        self.e.wln("handled = True");
                        self.e.wln("# fallthrough to return");
                        self.e.dedent();
                    }
                    if let Some((dfval, dftid)) = &v.default {
                        self.e.wln("if not handled:");
                        self.e.indent();
                        self.e.wln(&format!("# default case ({})", dfval));
                        self.emit_read_member_assign(*dftid, "value");
                        self.e.dedent();
                    } else {
                        self.e.wln(
                            "if not handled: raise ValueError('unknown variant tag: %r' % (tag,))",
                        );
                    }
                    self.e.wln(&format!("out = {}(tag=tag, value=value)", cls));
                    self.e.wln("return out");
                } else if let Some((_dfval, dftid)) = &v.default {
                    // No members but default present
                    self.emit_read_member_assign(*dftid, "value");
                    self.e.wln(&format!("return {}(tag=tag, value=value)", cls));
                } else {
                    self.e.wln("raise ValueError('variant has no alternatives')");
                }
            }
            _ => {
                self.e.wln("raise NotImplementedError()");
            }
        }
        self.e.dedent();
    }

    fn emit_write_fn(&mut self, tid: TypeID, name: &str) {
        let cls = sanitize_ident(name, "T");
        self.e.wln(&format!("def write_{}(w, obj):", cls));
        self.e.indent();
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Enum(e) => {
                let writem = self.py_write_prim(&e.ty);
                self.e.wln(&format!("w.{}(int(obj))", writem));
            }
            TypeKind::Bitfld(b) => {
                let underlying = self.e.module.lookup(b.ty).unwrap();
                let prim = match &underlying.kind {
                    TypeKind::Primitive(p) => p,
                    TypeKind::Enum(e) => &e.ty,
                    _ => panic!("invalid bitfield base"),
                };
                let writem = self.py_write_prim(prim);
                self.e.wln(&format!("w.{}(int(obj.value))", writem));
            }
            TypeKind::Pack(_) => {
                self.e.wln("w.write_raw(obj)");
            }
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    let expr = format!("obj.{}", sanitize_ident(mname, "T"));
                    self.emit_write_member(*mtid, &expr);
                }
            }
            TypeKind::Variant(v) => {
                let writem = self.py_write_prim(&v.ty);
                self.e.wln(&format!("w.{}(int(obj.tag))", writem));
                if !v.members.is_empty() {
                    for (val, vt) in &v.members {
                        self.e.wln(&format!("if int(obj.tag) == {}:", val));
                        self.e.indent();
                        self.emit_write_member(*vt, "obj.value");
                        self.e.wln("return");
                        self.e.dedent();
                    }
                    if let Some((_dfval, dftid)) = &v.default {
                        self.e.wln("# default branch");
                        self.emit_write_member(*dftid, "obj.value");
                        self.e.wln("return");
                    } else {
                        self.e.wln(
                            "raise ValueError('unknown variant tag for write: %r' % (obj.tag,))",
                        );
                    }
                } else if let Some((_dfval, dftid)) = &v.default {
                    self.emit_write_member(*dftid, "obj.value");
                } else {
                    self.e.wln("raise ValueError('variant has no alternatives')");
                }
            }
            _ => self.e.wln("raise NotImplementedError()"),
        }
        self.e.dedent();
    }

    fn emit_read_member(&mut self, tid: TypeID, lhs: &str) {
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(p) => {
                let m = self.py_read_prim(p);
                self.e.wln(&format!("{} = r.{}()", lhs, m));
            }
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("read_{}", sanitize_ident(name, "T"));
                    self.e.wln(&format!("{} = {}(r)", lhs, func));
                } else {
                    self.e.wln("raise NotImplementedError()  # anonymous composite");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            }) => {
                // size then elements
                let st = self.e.module.lookup(*size_type).unwrap();
                let sp = match &st.kind {
                    TypeKind::Primitive(p) => p,
                    _ => panic!("size_type not primitive"),
                };
                let readm = self.py_read_prim(sp);
                // special case: bytes for u8
                let vt = self.e.module.lookup(*value_type).unwrap();
                let is_u8 = matches!(vt.kind, TypeKind::Primitive(Primitive::U8));
                self.e.wln(&format!("__n = r.{}()", readm));
                if is_u8 {
                    self.e.wln(&format!("{} = r.read_bytes(__n)", lhs));
                } else {
                    self.e.wln(&format!("{} = []", lhs));
                    self.e.wln("for _ in range(int(__n)):");
                    self.e.indent();
                    self.emit_read_member_push(*value_type, lhs);
                    self.e.dedent();
                }
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                self.e.wln(&format!("{} = []", lhs));
                self.e.wln(&format!("for _ in range({}):", count));
                self.e.indent();
                self.emit_read_member_push(*value_type, lhs);
                self.e.dedent();
            }
            TypeKind::Alias(inner) => {
                let _ = inner; // alias not supported yet
                self.e.wln("raise NotImplementedError()  # alias");
            }
        }
    }

    fn emit_read_member_assign(&mut self, tid: TypeID, lhs_ident: &str) {
        // Write single assignment: lhs_ident = <read value>
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(p) => {
                let m = self.py_read_prim(p);
                self.e.wln(&format!("{} = r.{}()", lhs_ident, m));
            }
            _ => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("read_{}", sanitize_ident(name, "T"));
                    self.e.wln(&format!("{} = {}(r)", lhs_ident, func));
                } else {
                    // Arrays or anonymous types don't occur here in variant alts
                    self.e.wln("raise NotImplementedError()");
                }
            }
        }
    }

    fn emit_read_member_push(&mut self, tid: TypeID, lhs_list: &str) {
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(p) => {
                let m = self.py_read_prim(p);
                self.e.wln(&format!("{}.append(r.{}())", lhs_list, m));
            }
            _ => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("read_{}", sanitize_ident(name, "T"));
                    self.e.wln(&format!("{}.append({}(r))", lhs_list, func));
                } else {
                    self.e.wln("raise NotImplementedError()");
                }
            }
        }
    }

    fn emit_write_member(&mut self, tid: TypeID, expr: &str) {
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(p) => {
                let m = self.py_write_prim(p);
                self.e.wln(&format!("w.{}({})", m, expr));
            }
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("write_{}", sanitize_ident(name, "T"));
                    self.e.wln(&format!("{}(w, {})", func, expr));
                } else {
                    self.e.wln("raise NotImplementedError()  # anonymous composite");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            }) => {
                let st = self.e.module.lookup(*size_type).unwrap();
                let sp = match &st.kind {
                    TypeKind::Primitive(p) => p,
                    _ => panic!("size_type not primitive"),
                };
                let writem = self.py_write_prim(sp);
                // special u8 bytes case
                let vt = self.e.module.lookup(*value_type).unwrap();
                let is_u8 = matches!(vt.kind, TypeKind::Primitive(Primitive::U8));
                self.e.wln(&format!("w.{}(len({}))", writem, expr));
                if is_u8 {
                    self.e.wln(&format!("w.write_bytes({})", expr));
                } else {
                    self.e.wln(&format!("for __v in {}:", expr));
                    self.e.indent();
                    self.emit_write_member(*value_type, "__v");
                    self.e.dedent();
                }
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                self.e.wln(&format!("for __i in range({}):", count));
                self.e.indent();
                let item = format!("{}[__i]", expr);
                self.emit_write_member(*value_type, &item);
                self.e.dedent();
            }
            TypeKind::Alias(inner) => {
                let _ = inner;
                self.e.wln("raise NotImplementedError()  # alias");
            }
        }
    }
}
