//! Rust backend: emits a single module with all types and helpers.
//!
//! Highlights
//! - Generates `read_*`/`write_*` for named types.
//! - For sequences and variants, also generates lightweight view types
//!   (`<Name>View<'a>`) and corresponding `write_*View` helpers so callers
//!   can encode without constructing fully-owned values.
use crate::codegen::common::{TextEmitter, sanitize_ident};
use crate::module::*;
use crate::tokens::Span;

/// Public entry: emit a single Rust module with all types and read/write helpers.
pub fn emit_rust(
    module: Module,
    mut file: impl std::io::Write,
) -> Result<(), super::GeneratorError> {
    let mut e = RustEmitter::new(&module);
    e.emit_preamble();
    e.emit_all_types();
    let string = e.finish();

    file.write_all(string.as_bytes())?;
    Ok(())
}

/// Small wrapper that delegates to `TextEmitter` and holds codegen logic.
struct RustEmitter<'a> {
    e: TextEmitter<'a>,
}

impl<'a> RustEmitter<'a> {
    fn new(module: &'a Module) -> Self {
        Self {
            e: TextEmitter::new(module),
        }
    }

    fn finish(self) -> String {
        self.e.finish()
    }

    /// Emit module preamble and primitive read/write helpers.
    fn emit_preamble(&mut self) {
        let ns = sanitize_ident(&self.e.module.name, "module");
        self.e.wln("// Generated by jaw. Do not edit.");
        self.e.wln("#[allow(dead_code)]");
        self.e.wln("#[allow(non_snake_case)]");
        self.e.wln(&format!("pub mod {} {{", ns));
        self.e.indent();
        self.e.wln("use std::io::{self, Read, Write};");
        self.e.wln("");
        // Primitive readers
        for (name, bits) in [
            ("u8", 1usize),
            ("i8", 1usize),
            ("u16", 2usize),
            ("i16", 2usize),
            ("u32", 4usize),
            ("i32", 4usize),
            ("u64", 8usize),
            ("i64", 8usize),
            ("f32", 4usize),
            ("f64", 8usize),
        ] {
            self.e.wln(&format!(
                "pub fn read_{}<R: Read>(r: &mut R) -> io::Result<{}> {{",
                name, name
            ));
            self.e.indent();
            if bits == 1 {
                self.e.wln("let mut b = [0u8; 1];");
                self.e.wln("r.read_exact(&mut b)?;");
                match name {
                    "u8" => self.e.wln("Ok(b[0])"),
                    "i8" => self.e.wln("Ok(b[0] as i8)"),
                    _ => {}
                }
            } else {
                self.e.wln(&format!("let mut b = [0u8; {}];", bits));
                self.e.wln("r.read_exact(&mut b)?;");
                let from = match name {
                    "u16" => "u16::from_le_bytes(b)",
                    "i16" => "i16::from_le_bytes(b)",
                    "u32" => "u32::from_le_bytes(b)",
                    "i32" => "i32::from_le_bytes(b)",
                    "u64" => "u64::from_le_bytes(b)",
                    "i64" => "i64::from_le_bytes(b)",
                    "f32" => "f32::from_le_bytes(b)",
                    "f64" => "f64::from_le_bytes(b)",
                    _ => unreachable!(),
                };
                self.e.wln(&format!("Ok({})", from));
            }
            self.e.dedent();
            self.e.wln("}");
        }
        self.e.wln("");
        // Primitive writers
        for name in [
            "u8", "i8", "u16", "i16", "u32", "i32", "u64", "i64", "f32", "f64",
        ] {
            self.e.wln(&format!(
                "pub fn write_{}<W: Write>(w: &mut W, v: {}) -> io::Result<()> {{",
                name, name
            ));
            self.e.indent();
            match name {
                "u8" | "i8" => self.e.wln("w.write_all(&[v as u8])"),
                "u16" => self.e.wln("w.write_all(&v.to_le_bytes())"),
                "i16" => self.e.wln("w.write_all(&v.to_le_bytes())"),
                "u32" => self.e.wln("w.write_all(&v.to_le_bytes())"),
                "i32" => self.e.wln("w.write_all(&v.to_le_bytes())"),
                "u64" => self.e.wln("w.write_all(&v.to_le_bytes())"),
                "i64" => self.e.wln("w.write_all(&v.to_le_bytes())"),
                "f32" => self.e.wln("w.write_all(&v.to_le_bytes())"),
                "f64" => self.e.wln("w.write_all(&v.to_le_bytes())"),
                _ => unreachable!(),
            }
            self.e.dedent();
            self.e.wln("}");
        }
        self.e.wln("");
    }

    /// Emit all named types and their helpers in dependency order.
    fn emit_all_types(&mut self) {
        let order: Vec<TypeID> = self.e.module.type_order.clone();
        for tid in order.into_iter() {
            let Some(ty) = self.e.module.lookup(tid) else {
                continue;
            };
            let Some(name) = self.e.name_of(tid).map(|x| x.to_string()) else {
                continue;
            };
            if let Span::Builtin = ty.defined_at {
                continue;
            }

            match &ty.kind {
                TypeKind::Enum(e) => self.emit_enum(&name, e),
                TypeKind::Bitfld(b) => self.emit_bitfield(&name, b),
                TypeKind::Pack(p) => self.emit_pack(&name, p),
                TypeKind::Sequence(s) => {
                    self.emit_sequence_type(&name, s);
                    self.emit_sequence_view(&name, s);
                }
                TypeKind::Variant(v) => {
                    self.emit_variant_type(&name, v);
                    self.emit_variant_view(&name, v);
                }
                TypeKind::Alias(_) => {}
                TypeKind::Primitive(_) | TypeKind::DynamicArray(_) | TypeKind::FixedArray(_) => {}
            }
            self.e.wln("");
            self.emit_read_fn(tid, &name);
            self.emit_write_fn(tid, &name);
            if matches!(ty.kind, TypeKind::Sequence(_) | TypeKind::Variant(_)) {
                self.emit_write_fn_view(tid, &name);
            }
            self.e.wln("");
        }

        // close module
        self.e.dedent();
        let ns = sanitize_ident(&self.e.module.name, "module");
        self.e.wln(&format!("}} // mod {}", ns));
    }

    /// Rust primitive name for a `Primitive`.
    fn rust_primitive(&self, p: &Primitive) -> &'static str {
        match p {
            Primitive::U8 => "u8",
            Primitive::U16 => "u16",
            Primitive::U32 => "u32",
            Primitive::U64 => "u64",
            Primitive::I8 => "i8",
            Primitive::I16 => "i16",
            Primitive::I32 => "i32",
            Primitive::I64 => "i64",
            Primitive::F32 => "f32",
            Primitive::F64 => "f64",
        }
    }

    /// Rust type used for a field inside a `pack`.
    fn rust_type_for_pack_field(&self, tid: TypeID) -> String {
        let ty = self.e.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.rust_primitive(p).to_string(),
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    sanitize_ident(name, "T")
                } else {
                    "i32".to_string()
                }
            }
            TypeKind::DynamicArray(_) => {
                // Non-POD not allowed in pack; fallback
                "/*dyn*/Vec<i32>".to_string()
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type }) => {
                let elem = self.rust_type_for_pack_field(*value_type);
                format!("[{}; {}]", elem, count)
            }
            TypeKind::FixedArray(ArrayKind::Dynamic { .. }) => {
                // invalid combination for pack; fallback
                "/*invalid*/Vec<i32>".to_string()
            }
            TypeKind::Alias(inner) => {
                // Alias is not currently materialized by name; fallback
                let _ = inner;
                "i32".to_string()
            }
        }
    }

    /// Rust type used for a field inside a `seq`.
    fn rust_type_for_seq_field(&self, tid: TypeID) -> String {
        let ty = self.e.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.rust_primitive(p).to_string(),
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    sanitize_ident(name, "T")
                } else {
                    "i32".to_string()
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic { value_type, .. })
            | TypeKind::FixedArray(ArrayKind::Dynamic { value_type, .. }) => {
                let elem = self.rust_type_for_seq_field(*value_type);
                format!("Vec<{}>", elem)
            }
            TypeKind::FixedArray(ArrayKind::Fixed { value_type, .. })
            | TypeKind::DynamicArray(ArrayKind::Fixed { value_type, .. }) => {
                let elem = self.rust_type_for_seq_field(*value_type);
                format!("Vec<{}>", elem)
            }
            TypeKind::Alias(inner) => {
                let _ = inner;
                "i32".to_string()
            }
        }
    }

    /// Emit a Rust `enum` corresponding to a `.jaw enum`.
    fn emit_enum(&mut self, name: &str, e: &Enum) {
        let rs_name = sanitize_ident(name, "T");
        let under = self.rust_primitive(&e.ty);
        self.e.wln(&format!("#[repr({})]", under));
        self.e.wln("#[derive(Copy, Clone, Debug, PartialEq, Eq)]");
        self.e.wln(&format!("pub enum {} {{", rs_name));
        self.e.indent();
        for (mname, val) in &e.members {
            let vname = sanitize_ident(mname, "T");
            self.e.wln(&format!("{} = {},", vname, val));
        }
        if let Some((dname, dval)) = &e.default {
            let vname = sanitize_ident(dname, "T");
            self.e.wln(&format!("{} = {},", vname, dval));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    /// Emit a Rust bitfield wrapper with simple accessors.
    fn emit_bitfield(&mut self, name: &str, b: &Bitfld) {
        let rs_name = sanitize_ident(name, "T");
        let underlying = self.e.module.lookup(b.ty).unwrap();
        let underlying_rs = match &underlying.kind {
            TypeKind::Primitive(p) => self.rust_primitive(p).to_string(),
            TypeKind::Enum(e) => self.rust_primitive(&e.ty).to_string(),
            _ => "u32".to_string(),
        };
        self.e.wln(&format!("#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)] pub struct {} {{ pub value: {} }}", rs_name, underlying_rs));
        self.e.wln(&format!("impl {} {{", rs_name));
        self.e.indent();
        for (fname, fty, range) in &b.members {
            let width = range.end() - range.start() + 1;
            let shift = range.start();
            let mask_val: u128 = if width >= 128 {
                u128::MAX
            } else {
                (1u128 << width) - 1
            };
            let ret_ty = {
                let ty = self.e.module.lookup(*fty).unwrap();
                match &ty.kind {
                    TypeKind::Primitive(p) => self.rust_primitive(p).to_string(),
                    TypeKind::Enum(e) => self.rust_primitive(&e.ty).to_string(),
                    _ => "u32".to_string(),
                }
            };
            let fname_s = sanitize_ident(fname, "T");
            self.e.wln(&format!(
                "pub fn get_{}(&self) -> {} {{ (((self.value as u128) >> {}) & ({})) as {} }}",
                fname_s, ret_ty, shift, mask_val, ret_ty
            ));
            self.e.wln(&format!(
                "pub fn set_{}(&mut self, v: {}) {{ let cleared = (self.value as u128) & !((( {}) ) << {}); let newv = cleared | (((v as u128) & ({})) << {}); self.value = newv as {}; }}",
                fname_s, ret_ty, mask_val, shift, mask_val, shift, underlying_rs
            ));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    /// Emit a `#[repr(C)]` struct for POD packs.
    fn emit_pack(&mut self, name: &str, p: &Pack) {
        let rs_name = sanitize_ident(name, "T");
        self.e.wln(&format!(
            "#[derive(Debug, Clone)]\n#[repr(C)]\npub struct {} {{",
            rs_name
        ));
        self.e.indent();
        for (mname, mtid) in &p.members {
            let t = self.rust_type_for_pack_field(*mtid);
            self.e
                .wln(&format!("pub {}: {},", sanitize_ident(mname, "T"), t));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    /// Emit an owned Rust struct for a sequence.
    fn emit_sequence_type(&mut self, name: &str, s: &Sequence) {
        let rs_name = sanitize_ident(name, "T");
        self.e.wln(&format!(
            "#[derive(Debug, Clone)] pub struct {} {{",
            rs_name
        ));
        self.e.indent();
        for (mname, mtid) in &s.members {
            let t = self.rust_type_for_seq_field(*mtid);
            self.e
                .wln(&format!("pub {}: {},", sanitize_ident(mname, "T"), t));
        }
        self.e.dedent();
        self.e.wln("}");
    }
    
    /// Emit a borrowed view struct for a sequence.
    fn emit_sequence_view(&mut self, name: &str, s: &Sequence) {
        let rs_name = sanitize_ident(name, "T");
        let view_name = format!("{}View", rs_name);
        self.e.wln(&format!(
            "#[derive(Debug, Clone, Copy)] pub struct {}<'a> {{",
            view_name
        ));
        self.e.indent();
        for (mname, mtid) in &s.members {
            let t = self.rust_type_for_view_field(*mtid, "'a");
            self.e
                .wln(&format!("pub {}: {},", sanitize_ident(mname, "T"), t));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    /// Emit an owned Rust enum for a variant with payload types.
    fn emit_variant_type(&mut self, name: &str, v: &Variant) {
        let rs_name = sanitize_ident(name, "T");
        self.e
            .wln(&format!("#[derive(Debug, Clone)] pub enum {} {{", rs_name));
        self.e.indent();
        for (idx, (_val, vt)) in v.members.iter().enumerate() {
            let t = self.rust_type_for_seq_field(*vt);
            self.e.wln(&format!("Alt{}({}),", idx, t));
        }
        if let Some((_dv, dt)) = &v.default {
            let t = self.rust_type_for_seq_field(*dt);
            self.e.wln(&format!("DefaultAlt({}),", t));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    /// Emit a borrowed view enum for a variant.
    fn emit_variant_view(&mut self, name: &str, v: &Variant) {
        let rs_name = sanitize_ident(name, "T");
        let view_name = format!("{}View", rs_name);
        self.e
            .wln(&format!("#[derive(Debug, Clone, Copy)] pub enum {}<'a> {{", view_name));
        self.e.indent();
        for (idx, (_val, vt)) in v.members.iter().enumerate() {
            let t = self.rust_type_for_view_field(*vt, "'a");
            self.e.wln(&format!("Alt{}({}),", idx, t));
        }
        if let Some((_dv, dt)) = &v.default {
            let t = self.rust_type_for_view_field(*dt, "'a");
            self.e.wln(&format!("DefaultAlt({}),", t));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    /// Emit a top-level `read_<Name>` function for the named type.
    fn emit_read_fn(&mut self, tid: TypeID, name: &str) {
        let rs_name = sanitize_ident(name, "T");
        self.e.wln(&format!(
            "pub fn read_{}<R: Read>(r: &mut R) -> io::Result<{}> {{",
            rs_name, rs_name
        ));
        self.e.indent();
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Enum(e) => {
                let prim_fn = self.rs_read_prim(&e.ty);
                self.e.wln(&format!("let tmp = {}(r)?;", prim_fn));
                if e.members.is_empty() && e.default.is_none() {
                    self.e.wln("return Err(io::Error::new(io::ErrorKind::InvalidData, \"enum has no members\"));");
                } else {
                    self.e.wln("let out = match tmp { ");
                    self.e.indent();
                    for (mname, val) in &e.members {
                        let vname = sanitize_ident(mname, "T");
                        self.e.wln(&format!("{} => {}::{},", val, rs_name, vname));
                    }
                    if let Some((dname, _dval)) = &e.default {
                        let vname = sanitize_ident(dname, "T");
                        self.e.wln(&format!("_ => {}::{},", rs_name, vname));
                    } else {
                        self.e.wln("_ => return Err(io::Error::new(io::ErrorKind::InvalidData, \"invalid enum discriminant\")),");
                    }
                    self.e.dedent();
                    self.e.wln("};");
                    self.e.wln("Ok(out)");
                }
            }
            TypeKind::Bitfld(b) => {
                let underlying = self.e.module.lookup(b.ty).unwrap();
                let prim = match &underlying.kind {
                    TypeKind::Primitive(p) => p,
                    TypeKind::Enum(e) => &e.ty,
                    _ => panic!("invalid bitfield base"),
                };
                let prim_fn = self.rs_read_prim(prim);
                self.e.wln(&format!("let tmp = {}(r)?;", prim_fn));
                self.e.wln(&format!("Ok({} {{ value: tmp }})", rs_name));
            }
            TypeKind::Pack(_) => {
                // Read as one
                self.e.wln(&format!(
                    "let mut ret = std::mem::MaybeUninit::<{}>::zeroed();",
                    rs_name
                ));
                self.e.wln(&format!("let mut slice = unsafe {{ std::slice::from_raw_parts_mut(ret.as_mut_ptr() as *mut u8, std::mem::size_of::<{}>()) }};", rs_name));
                self.e.wln("r.read_exact(&mut slice)?;");
                self.e.wln("Ok(unsafe { ret.assume_init() })");
            }
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    let lhs = format!("{}", sanitize_ident(mname, "T"));
                    self.emit_read_member(*mtid, &lhs);
                }
                self.e.wln("Ok(");
                self.e.indent();
                self.e.wln(&format!("{} {{", rs_name));
                self.e.indent();
                for (mname, _mtid) in &s.members {
                    let lhs = sanitize_ident(mname, "T");
                    self.e.wln(&format!("{}: {},", lhs, lhs));
                }
                self.e.dedent();
                self.e.wln("}");
                self.e.dedent();
                self.e.wln(")");
            }
            TypeKind::Variant(v) => {
                let prim_fn = self.rs_read_prim(&v.ty);
                self.e.wln(&format!("let tag = {}(r)?;", prim_fn));
                if !v.members.is_empty() {
                    for (idx, (val, vt)) in v.members.iter().enumerate() {
                        self.e.wln(&format!("if tag == {} {{", val));
                        self.e.indent();
                        self.emit_read_member_assign(*vt, "__value");
                        self.e
                            .wln(&format!("return Ok({}::Alt{}(__value));", rs_name, idx));
                        self.e.dedent();
                        self.e.wln("}");
                    }
                    if let Some((_dfv, dftid)) = &v.default {
                        self.emit_read_member_assign(*dftid, "__value");
                        self.e
                            .wln(&format!("return Ok({}::DefaultAlt(__value));", rs_name));
                    } else {
                        self.e.wln("return Err(io::Error::new(io::ErrorKind::InvalidData, \"unknown variant tag\"));");
                    }
                } else if let Some((_dfv, dftid)) = &v.default {
                    self.emit_read_member_assign(*dftid, "__value");
                    self.e.wln(&format!("Ok({}::DefaultAlt(__value))", rs_name));
                } else {
                    self.e.wln("return Err(io::Error::new(io::ErrorKind::InvalidData, \"variant has no alternatives\"));");
                }
            }
            _ => {
                self.e.wln("return Err(io::Error::new(io::ErrorKind::Other, \"unsupported top-level type\"));");
            }
        }
        self.e.dedent();
        self.e.wln("}");
    }

    /// Emit a top-level `write_<Name>` function for the named type.
    fn emit_write_fn(&mut self, tid: TypeID, name: &str) {
        let rs_name = sanitize_ident(name, "T");
        self.e.wln(&format!(
            "pub fn write_{}<W: Write>(w: &mut W, v: &{}) -> io::Result<()> {{",
            rs_name, rs_name
        ));
        self.e.indent();
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Enum(e) => {
                let write_prim = self.rs_write_prim(&e.ty);
                self.e.wln(&format!(
                    "{}(w, *v as {})",
                    write_prim,
                    self.rust_primitive(&e.ty)
                ));
                self.e.wln(".and(Ok(()))");
            }
            TypeKind::Bitfld(b) => {
                let underlying = self.e.module.lookup(b.ty).unwrap();
                let prim = match &underlying.kind {
                    TypeKind::Primitive(p) => p,
                    TypeKind::Enum(e) => &e.ty,
                    _ => panic!("invalid bitfield base"),
                };
                let write_prim = self.rs_write_prim(prim);
                self.e.wln(&format!("{}(w, v.value)", write_prim));
                self.e.wln(".and(Ok(()))");
            }
            TypeKind::Pack(_) => {
                self.e.wln(&format!("let slice = unsafe {{ std::slice::from_raw_parts( v as *const _ as *const u8, std::mem::size_of::<{}>()) }};", rs_name));
                self.e.wln("w.write_all(slice)");
            }
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    let expr = format!("v.{}", sanitize_ident(mname, "T"));
                    self.emit_write_member(*mtid, &expr);
                }
                self.e.wln("Ok(())");
            }
            TypeKind::Variant(v) => {
                let write_prim = self.rs_write_prim(&v.ty);
                // we need to discover tag from variant index; users must pass correctly tagged variant
                // There is no stored tag; we must compute from order.
                // Generate a match to write tag and payload.
                self.e.wln("match v {");
                self.e.indent();
                for (idx, (val, vt)) in v.members.iter().enumerate() {
                    self.e.wln(&format!("{}::Alt{}(__x) => {{", rs_name, idx));
                    self.e.indent();
                    self.e.wln(&format!("{}(w, {})?;", write_prim, val));
                    self.emit_write_member(*vt, "__x");
                    self.e.wln("Ok(())");
                    self.e.dedent();
                    self.e.wln("}");
                }
                if let Some((dfv, dt)) = &v.default {
                    self.e.wln(&format!("{}::DefaultAlt(__x) => {{", rs_name));
                    self.e.indent();
                    self.e.wln(&format!("{}(w, {})?;", write_prim, dfv));
                    self.emit_write_member(*dt, "__x");
                    self.e.wln("Ok(())");
                    self.e.dedent();
                    self.e.wln("}");
                }
                self.e.dedent();
                self.e.wln("}");
            }
            _ => {
                self.e.wln(
                    "Err(io::Error::new(io::ErrorKind::Other, \"unsupported top-level type\"))",
                );
            }
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_write_fn_view(&mut self, tid: TypeID, name: &str) {
        let rs_name = sanitize_ident(name, "T");
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Sequence(s) => {
                let view_name = format!("{}View", rs_name);
                self.e.wln(&format!(
                    "pub fn write_{}View<W: Write>(w: &mut W, v: &{}<'_>) -> io::Result<()> {{",
                    rs_name, view_name
                ));
                self.e.indent();
                for (mname, mtid) in &s.members {
                    let expr = format!("v.{}", sanitize_ident(mname, "T"));
                    self.emit_write_member_view(*mtid, &expr);
                }
                self.e.wln("Ok(())");
                self.e.dedent();
                self.e.wln("}");
            }
            TypeKind::Variant(v) => {
                let view_name = format!("{}View", rs_name);
                let write_prim = self.rs_write_prim(&v.ty);
                self.e.wln(&format!(
                    "pub fn write_{}View<W: Write>(w: &mut W, v: &{}<'_>) -> io::Result<()> {{",
                    rs_name, view_name
                ));
                self.e.indent();
                self.e.wln("match v {");
                self.e.indent();
                for (idx, (val, vt)) in v.members.iter().enumerate() {
                    self.e.wln(&format!("{}::Alt{}(__x) => {{", view_name, idx));
                    self.e.indent();
                    self.e.wln(&format!("{}(w, {})?;", write_prim, val));
                    // payload
                    self.emit_write_member_view(*vt, "__x");
                    self.e.wln("Ok(())");
                    self.e.dedent();
                    self.e.wln("}");
                }
                if let Some((dfv, dt)) = &v.default {
                    self.e.wln(&format!("{}::DefaultAlt(__x) => {{", view_name));
                    self.e.indent();
                    self.e.wln(&format!("{}(w, {})?;", write_prim, dfv));
                    self.emit_write_member_view(*dt, "__x");
                    self.e.wln("Ok(())");
                    self.e.dedent();
                    self.e.wln("}");
                }
                self.e.dedent();
                self.e.wln("}");
                self.e.dedent();
                self.e.wln("}");
            }
            _ => {}
        }
    }

    /// Helper: function name for reading a primitive.
    fn rs_read_prim(&self, p: &Primitive) -> &'static str {
        match p {
            Primitive::U8 => "read_u8",
            Primitive::U16 => "read_u16",
            Primitive::U32 => "read_u32",
            Primitive::U64 => "read_u64",
            Primitive::I8 => "read_i8",
            Primitive::I16 => "read_i16",
            Primitive::I32 => "read_i32",
            Primitive::I64 => "read_i64",
            Primitive::F32 => "read_f32",
            Primitive::F64 => "read_f64",
        }
    }

    /// Helper: function name for writing a primitive.
    fn rs_write_prim(&self, p: &Primitive) -> &'static str {
        match p {
            Primitive::U8 => "write_u8",
            Primitive::U16 => "write_u16",
            Primitive::U32 => "write_u32",
            Primitive::U64 => "write_u64",
            Primitive::I8 => "write_i8",
            Primitive::I16 => "write_i16",
            Primitive::I32 => "write_i32",
            Primitive::I64 => "write_i64",
            Primitive::F32 => "write_f32",
            Primitive::F64 => "write_f64",
        }
    }

    fn rust_type_for_view_field(&self, tid: TypeID, lt: &str) -> String {
        let ty = self.e.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.rust_primitive(p).to_string(),
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    format!("&{} {}", lt, sanitize_ident(name, "T"))
                } else {
                    format!("&{} i32", lt)
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic { value_type, .. })
            | TypeKind::FixedArray(ArrayKind::Dynamic { value_type, .. }) => {
                let elem = self.rust_type_for_view_array_elem(*value_type);
                format!("&{} [{}]", lt, elem)
            }
            TypeKind::FixedArray(ArrayKind::Fixed { value_type, .. })
            | TypeKind::DynamicArray(ArrayKind::Fixed { value_type, .. }) => {
                let elem = self.rust_type_for_view_array_elem(*value_type);
                format!("&{} [{}]", lt, elem)
            }
            TypeKind::Alias(_inner) => {
                // alias not supported
                "i32".to_string()
            }
        }
    }

    fn rust_type_for_view_array_elem(&self, tid: TypeID) -> String {
        let ty = self.e.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.rust_primitive(p).to_string(),
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    sanitize_ident(name, "T")
                } else {
                    "i32".to_string()
                }
            }
            // Nested arrays represented the same as sequence fields (Vec<...>)
            TypeKind::DynamicArray(_) | TypeKind::FixedArray(_) => {
                self.rust_type_for_seq_field(tid)
            }
            TypeKind::Alias(_inner) => "i32".to_string(),
        }
    }

    fn emit_read_member(&mut self, tid: TypeID, lhs_ident: &str) {
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(p) => {
                let m = self.rs_read_prim(p);
                self.e.wln(&format!("let {} = {}(r)?;", lhs_ident, m));
            }
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("read_{}", sanitize_ident(name, "T"));
                    self.e.wln(&format!("let {} = {}(r)?;", lhs_ident, func));
                } else {
                    self.e.wln("return Err(io::Error::new(io::ErrorKind::Other, \"anonymous composite not supported\"));");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            }) => {
                let st = self.e.module.lookup(*size_type).unwrap();
                let sp = match &st.kind {
                    TypeKind::Primitive(p) => p,
                    _ => panic!("size_type not primitive"),
                };
                let readm = self.rs_read_prim(sp);
                let vt = self.e.module.lookup(*value_type).unwrap();
                let is_u8 = matches!(vt.kind, TypeKind::Primitive(Primitive::U8));
                self.e.wln(&format!("let __n = {}(r)? as usize;", readm));
                if is_u8 {
                    self.e
                        .wln(&format!("let mut {} = vec![0u8; __n];", lhs_ident));
                    self.e.wln(&format!("r.read_exact(&mut {})?;", lhs_ident));
                } else {
                    let elem_read = if let Some(name) = self.e.name_of(*value_type) {
                        format!("read_{}(r)?", sanitize_ident(name, "T"))
                    } else {
                        match &vt.kind {
                            TypeKind::Primitive(p) => format!("{}(r)?", self.rs_read_prim(p)),
                            _ => "return Err(io::Error::new(io::ErrorKind::Other, \"anonymous type in array\"));".to_string(),
                        }
                    };
                    self.e
                        .wln(&format!("let mut {} = Vec::with_capacity(__n);", lhs_ident));
                    self.e.wln("for _ in 0..__n {");
                    self.e.indent();
                    self.e.wln(&format!("{} .push({});", lhs_ident, elem_read));
                    self.e.dedent();
                    self.e.wln("}");
                }
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                // Represented in sequences as Vec
                let vt = self.e.module.lookup(*value_type).unwrap();
                let elem_read = if let Some(name) = self.e.name_of(*value_type) {
                    format!("read_{}(r)?", sanitize_ident(name, "T"))
                } else {
                    match &vt.kind {
                        TypeKind::Primitive(p) => format!("{}(r)?", self.rs_read_prim(p)),
                        _ => "return Err(io::Error::new(io::ErrorKind::Other, \"anonymous type in array\"));".to_string(),
                    }
                };
                self.e.wln(&format!(
                    "let mut {} = Vec::with_capacity({});",
                    lhs_ident, count
                ));
                self.e.wln(&format!("for _ in 0..{} {{", count));
                self.e.indent();
                self.e.wln(&format!("{} .push({});", lhs_ident, elem_read));
                self.e.dedent();
                self.e.wln("}");
            }
            TypeKind::Alias(_inner) => {
                self.e.wln(
                    "return Err(io::Error::new(io::ErrorKind::Other, \"alias not supported\"));",
                );
            }
        }
    }

    fn emit_read_member_assign(&mut self, tid: TypeID, lhs_ident: &str) {
        // lhs_ident must be a simple identifier, not a path
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(p) => {
                let m = self.rs_read_prim(p);
                self.e.wln(&format!("let {} = {}(r)?;", lhs_ident, m));
            }
            _ => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("read_{}", sanitize_ident(name, "T"));
                    self.e.wln(&format!("let {} = {}(r)?;", lhs_ident, func));
                } else {
                    self.e.wln("return Err(io::Error::new(io::ErrorKind::Other, \"anonymous composite\"));");
                }
            }
        }
    }

    fn emit_write_member(&mut self, tid: TypeID, expr: &str) {
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(p) => {
                let m = self.rs_write_prim(p);
                self.e.wln(&format!("{}(w, {})?;", m, expr));
            }
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("write_{}", sanitize_ident(name, "T"));
                    self.e.wln(&format!("{}(w, &{})?;", func, expr));
                } else {
                    self.e.wln("return Err(io::Error::new(io::ErrorKind::Other, \"anonymous composite\"));");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            }) => {
                let st = self.e.module.lookup(*size_type).unwrap();
                let sp = match &st.kind {
                    TypeKind::Primitive(p) => p,
                    _ => panic!("size_type not primitive"),
                };
                let write_m = self.rs_write_prim(sp);
                let vt = self.e.module.lookup(*value_type).unwrap();
                let is_u8 = matches!(vt.kind, TypeKind::Primitive(Primitive::U8));
                self.e.wln(&format!(
                    "{}(w, {}.len() as {})?;",
                    write_m,
                    expr,
                    self.rust_primitive(sp)
                ));
                if is_u8 {
                    self.e.wln(&format!("w.write_all(&{})?;", expr));
                } else {
                    self.e.wln(&format!("for __v in {}.iter() {{", expr));
                    self.e.indent();
                    self.emit_write_member(*value_type, "*__v");
                    self.e.dedent();
                    self.e.wln("}");
                }
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                // seq representation uses Vec here
                self.e.wln(&format!("for __i in 0..{} {{", count));
                self.e.indent();
                let item = format!("{}[__i]", expr);
                self.emit_write_member(*value_type, &item);
                self.e.dedent();
                self.e.wln("}");
            }
            TypeKind::Alias(_inner) => {
                self.e.wln(
                    "return Err(io::Error::new(io::ErrorKind::Other, \"alias not supported\"));",
                );
            }
        }
    }

    fn emit_write_member_view(&mut self, tid: TypeID, expr: &str) {
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(p) => {
                let m = self.rs_write_prim(p);
                self.e.wln(&format!("{}(w, {})?;", m, expr));
            }
            TypeKind::Enum(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("write_{}", sanitize_ident(name, "T"));
                    // enum view field is by value; pass reference
                    self.e.wln(&format!("{}(w, &{})?;", func, expr));
                } else {
                    self.e.wln("return Err(io::Error::new(io::ErrorKind::Other, \"anonymous enum in view\"));");
                }
            }
            TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("write_{}", sanitize_ident(name, "T"));
                    // expr is a &T already in view types
                    self.e.wln(&format!("{}(w, {})?;", func, expr));
                } else {
                    self.e.wln("return Err(io::Error::new(io::ErrorKind::Other, \"anonymous composite in view\"));");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            }) => {
                let st = self.e.module.lookup(*size_type).unwrap();
                let sp = match &st.kind {
                    TypeKind::Primitive(p) => p,
                    _ => panic!("size_type not primitive"),
                };
                let write_m = self.rs_write_prim(sp);
                let vt = self.e.module.lookup(*value_type).unwrap();
                let is_u8 = matches!(vt.kind, TypeKind::Primitive(Primitive::U8));
                self.e.wln(&format!(
                    "{}(w, {}.len() as {})?;",
                    write_m,
                    expr,
                    self.rust_primitive(sp)
                ));
                if is_u8 {
                    self.e.wln(&format!("w.write_all({})?;", expr));
                } else {
                    self.e.wln(&format!("for __v in {}.iter() {{", expr));
                    self.e.indent();
                    match &vt.kind {
                        TypeKind::Primitive(p) => {
                            let wm = self.rs_write_prim(p);
                            self.e.wln(&format!("{}(w, *__v)?;", wm));
                        }
                        _ => {
                            if let Some(nm) = self.e.name_of(*value_type) {
                                let func = format!("write_{}", sanitize_ident(nm, "T"));
                                self.e.wln(&format!("{}(w, __v)?;", func));
                            } else {
                                self.e.wln("return Err(io::Error::new(io::ErrorKind::Other, \"anonymous type in array view\"));");
                            }
                        }
                    }
                    self.e.dedent();
                    self.e.wln("}");
                }
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                // View uses slice; enforce expected length
                self.e.wln(&format!(
                    "if {}.len() != {} {{ return Err(io::Error::new(io::ErrorKind::InvalidData, \"fixed array length mismatch\")); }}",
                    expr, count
                ));
                let vt = self.e.module.lookup(*value_type).unwrap();
                let is_u8 = matches!(vt.kind, TypeKind::Primitive(Primitive::U8));
                if is_u8 {
                    self.e.wln(&format!("w.write_all({})?;", expr));
                } else {
                    self.e.wln(&format!("for __v in {}.iter() {{", expr));
                    self.e.indent();
                    match &vt.kind {
                        TypeKind::Primitive(p) => {
                            let wm = self.rs_write_prim(p);
                            self.e.wln(&format!("{}(w, *__v)?;", wm));
                        }
                        _ => {
                            if let Some(nm) = self.e.name_of(*value_type) {
                                let func = format!("write_{}", sanitize_ident(nm, "T"));
                                self.e.wln(&format!("{}(w, __v)?;", func));
                            } else {
                                self.e.wln("return Err(io::Error::new(io::ErrorKind::Other, \"anonymous type in array view\"));");
                            }
                        }
                    }
                    self.e.dedent();
                    self.e.wln("}");
                }
            }
            TypeKind::Alias(_inner) => {
                self.e.wln(
                    "return Err(io::Error::new(io::ErrorKind::Other, \"alias not supported in view\"));",
                );
            }
        }
    }
}
