//! Swift backend: emits a single Swift file with all types and helpers.
//!
//! Design choices per requirements:
//! - Swift 6 targets (iOS, visionOS, macOS), uses Foundation `Data`.
//! - Single `.swift` file output with a namespace `public enum <ModuleName> { ... }`.
//! - Little-endian assumed (native on modern Apple devices), no byte swapping.
//! - `UInt8` arrays are represented as `Data` (both dynamic and fixed-size).
//! - Other arrays are `[T]`. Fixed-size arrays are represented as `[T]` with length checks.
//! - Variants are Swift enums: `case alt0(T0)`, `case alt1(T1)`, `case defaultAlt(Td)`.
//! - Bitfields are `struct { value: Underlying }` with computed get/set helpers.

use crate::codegen::common::{sanitize_ident, TextEmitter};
use crate::module::*;
use crate::tokens::Span;
use std::collections::{HashMap, HashSet};

/// Public entry: emit a single Swift file with all types and read/write helpers.
pub fn emit_swift(
    module: Module,
    mut file: impl std::io::Write,
) -> Result<(), super::GeneratorError> {
    let mut e = SwiftEmitter::new(&module);
    e.emit_preamble();
    e.emit_all_types();
    let string = e.finish();
    file.write_all(string.as_bytes())?;
    Ok(())
}

struct SwiftEmitter<'a> {
    e: TextEmitter<'a>,
    fixed_arrays: HashMap<(String, usize), String>,
    fixed_datas: HashSet<usize>,
}

impl<'a> SwiftEmitter<'a> {
    fn new(module: &'a Module) -> Self {
        Self {
            e: TextEmitter::new(module),
            fixed_arrays: HashMap::new(),
            fixed_datas: HashSet::new(),
        }
    }

    fn finish(self) -> String { self.e.finish() }

    fn swift_ident(&self, raw: &str, default_: &str) -> String {
        // Base sanitize
        let base = sanitize_ident(raw, default_);
        // Swift reserved keywords and common contextual keywords
        const KW: &[&str] = &[
            "class","deinit","enum","extension","func","import","init","inout","let","operator",
            "protocol","static","struct","subscript","typealias","associatedtype","break","case","continue",
            "default","defer","do","else","fallthrough","for","guard","if","in","repeat","return","switch",
            "where","while","as","Any","catch","false","is","nil","rethrows","super","self","Self","throw",
            "throws","true","try","mutating","nonmutating","public","private","internal","open","fileprivate",
            "convenience","dynamic","final","lazy","optional","override","required","weak","willSet","didSet",
            "get","set","var"
        ];
        if KW.contains(&base.as_str()) { format!("_{}", base) } else { base }
    }

    fn emit_preamble(&mut self) {
        let ns = sanitize_ident(&self.e.module.name, "Module");
        self.e.wln("// Generated by jaw. Do not edit.");
        self.e.wln("import Foundation");
        self.e.wln("");
        self.e.wln(&format!("public enum {} {{", ns));
        self.e.indent();
        // Simple error type
        self.e.wln("public enum JawError: Error { case eof, invalidEnum, invalidVariant, anonymousType, lengthMismatch }");
        self.e.wln("");
        // Reader
        self.e.wln("public struct Reader {");
        self.e.indent();
        self.e.wln("public var data: Data");
        self.e.wln("public var pos: Int = 0");
        self.e.wln("public init(_ data: Data) { self.data = data }");
        self.e.wln("");
        // Primitive readers
        for (name, ty, size) in [
            ("U8", "UInt8", 1usize),
            ("I8", "Int8", 1usize),
            ("U16", "UInt16", 2usize),
            ("I16", "Int16", 2usize),
            ("U32", "UInt32", 4usize),
            ("I32", "Int32", 4usize),
            ("U64", "UInt64", 8usize),
            ("I64", "Int64", 8usize),
            ("F32", "Float", 4usize),
            ("F64", "Double", 8usize),
        ] {
            self.e.wln(&format!(
                "public mutating func read{}() throws -> {} {{",
                name, ty
            ));
            self.e.indent();
            self.e.wln(&format!(
                "guard pos + {} <= data.count else {{ throw JawError.eof }}",
                size
            ));
            if size == 1 {
                // For 1-byte, direct access
                if ty == "UInt8" {
                    self.e.wln("let v = data[pos]");
                } else {
                    self.e.wln("let v = Int8(bitPattern: data[pos])");
                }
            } else {
                // Load as native-endian, which is little-endian on Apple platforms
                self.e.wln(&format!(
                    "let v: {} = data.withUnsafeBytes {{ buf in\n            let base = buf.baseAddress!.advanced(by: pos)\n            return base.assumingMemoryBound(to: {}.self).pointee\n        }}",
                    ty, ty
                ));
            }
            self.e.wln(&format!("pos += {}", size));
            self.e.wln("return v");
            self.e.dedent();
            self.e.wln("}");
        }
        // bytes reader
        self.e.wln("public mutating func readBytes(_ n: Int) throws -> Data {");
        self.e.indent();
        self.e.wln("let end = pos + n");
        self.e.wln("guard end <= data.count else { throw JawError.eof }");
        self.e.wln("let out = data[pos..<end]");
        self.e.wln("pos = end");
        self.e.wln("return Data(out)");
        self.e.dedent();
        self.e.wln("}");
        self.e.dedent();
        self.e.wln("}");
        self.e.wln("");
        // Writer
        self.e.wln("public struct Writer {");
        self.e.indent();
        self.e.wln("public private(set) var out = Data()");
        self.e.wln("public init() {}");
        for (name, ty) in [
            ("U8", "UInt8"),
            ("I8", "Int8"),
            ("U16", "UInt16"),
            ("I16", "Int16"),
            ("U32", "UInt32"),
            ("I32", "Int32"),
            ("U64", "UInt64"),
            ("I64", "Int64"),
            ("F32", "Float"),
            ("F64", "Double"),
        ] {
            self.e.wln(&format!(
                "public mutating func write{}(_ v: {}) {{",
                name, ty
            ));
            self.e.indent();
            self.e.wln("var vv = v");
            self.e.wln("withUnsafeBytes(of: &vv) { out.append(contentsOf: $0) }");
            self.e.dedent();
            self.e.wln("}");
        }
        self.e.wln("public mutating func writeBytes(_ d: Data) { out.append(d) }");
        self.e.wln("public func data() -> Data { out }");
        self.e.dedent();
        self.e.wln("}");
        self.e.wln("");
    }

    fn swift_primitive(&self, p: &Primitive) -> &'static str {
        match p {
            Primitive::U8 => "UInt8",
            Primitive::U16 => "UInt16",
            Primitive::U32 => "UInt32",
            Primitive::U64 => "UInt64",
            Primitive::I8 => "Int8",
            Primitive::I16 => "Int16",
            Primitive::I32 => "Int32",
            Primitive::I64 => "Int64",
            Primitive::F32 => "Float",
            Primitive::F64 => "Double",
        }
    }

    fn sw_read_prim(&self, p: &Primitive) -> &'static str {
        match p {
            Primitive::U8 => "readU8",
            Primitive::U16 => "readU16",
            Primitive::U32 => "readU32",
            Primitive::U64 => "readU64",
            Primitive::I8 => "readI8",
            Primitive::I16 => "readI16",
            Primitive::I32 => "readI32",
            Primitive::I64 => "readI64",
            Primitive::F32 => "readF32",
            Primitive::F64 => "readF64",
        }
    }

    fn sw_write_prim(&self, p: &Primitive) -> &'static str {
        match p {
            Primitive::U8 => "writeU8",
            Primitive::U16 => "writeU16",
            Primitive::U32 => "writeU32",
            Primitive::U64 => "writeU64",
            Primitive::I8 => "writeI8",
            Primitive::I16 => "writeI16",
            Primitive::I32 => "writeI32",
            Primitive::I64 => "writeI64",
            Primitive::F32 => "writeF32",
            Primitive::F64 => "writeF64",
        }
    }

    fn type_for_pack_field(&mut self, tid: TypeID) -> String {
        let ty = self.e.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.swift_primitive(p).to_string(),
            TypeKind::Enum(_) | TypeKind::Bitfld(_) | TypeKind::Pack(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    sanitize_ident(name, "T")
                } else {
                    "Int32".to_string()
                }
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let vt = self.e.module.lookup(*value_type).unwrap();
                if matches!(vt.kind, TypeKind::Primitive(Primitive::U8)) {
                    self.fixed_data_type_name(*count as usize)
                } else {
                    let elem_sw = match &vt.kind {
                        TypeKind::Primitive(p) => self.swift_primitive(p).to_string(),
                        _ => {
                            if let Some(name) = self.e.name_of(*value_type) {
                                sanitize_ident(name, "T")
                            } else {
                                "Int32".to_string()
                            }
                        }
                    };
                    self.fixed_array_type_name(&elem_sw, *count as usize)
                }
            }
            _ => "Int32".to_string(),
        }
    }

    fn type_for_seq_field(&mut self, tid: TypeID) -> String {
        let ty = self.e.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.swift_primitive(p).to_string(),
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    sanitize_ident(name, "T")
                } else {
                    "Int32".to_string()
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic { value_type, .. })
            | TypeKind::FixedArray(ArrayKind::Dynamic { value_type, .. }) => {
                let vt = self.e.module.lookup(*value_type).unwrap();
                if matches!(vt.kind, TypeKind::Primitive(Primitive::U8)) {
                    "Data".to_string()
                } else {
                    let elem = match &vt.kind {
                        TypeKind::Primitive(p) => self.swift_primitive(p).to_string(),
                        _ => {
                            if let Some(name) = self.e.name_of(*value_type) {
                                sanitize_ident(name, "T")
                            } else {
                                "Int32".to_string()
                            }
                        }
                    };
                    format!("[{}]", elem)
                }
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let vt = self.e.module.lookup(*value_type).unwrap();
                if matches!(vt.kind, TypeKind::Primitive(Primitive::U8)) {
                    self.fixed_data_type_name(*count as usize)
                } else {
                    let elem_sw = match &vt.kind {
                        TypeKind::Primitive(p) => self.swift_primitive(p).to_string(),
                        _ => {
                            if let Some(name) = self.e.name_of(*value_type) {
                                sanitize_ident(name, "T")
                            } else {
                                "Int32".to_string()
                            }
                        }
                    };
                    self.fixed_array_type_name(&elem_sw, *count as usize)
                }
            }
            TypeKind::Alias(_) => "Int32".to_string(),
        }
    }

    fn emit_enum(&mut self, name: &str, e: &Enum) {
        let sw_name = sanitize_ident(name, "T");
        let under = self.swift_primitive(&e.ty);
        self.e.wln(&format!("public enum {}: {} {{", sw_name, under));
        self.e.indent();
        for (mname, val) in &e.members {
            let vname = sanitize_ident(mname, "T");
            self.e.wln(&format!("case {} = {}", vname, val));
        }
        if let Some((dname, dval)) = &e.default {
            let vname = sanitize_ident(dname, "T");
            self.e.wln(&format!("case {} = {}", vname, dval));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_bitfield(&mut self, name: &str, b: &Bitfld) {
        let sw_name = sanitize_ident(name, "T");
        let underlying = self.e.module.lookup(b.ty).unwrap();
        let underlying_sw = match &underlying.kind {
            TypeKind::Primitive(p) => self.swift_primitive(p).to_string(),
            TypeKind::Enum(e) => self.swift_primitive(&e.ty).to_string(),
            _ => "UInt32".to_string(),
        };
        self.e.wln(&format!("public struct {} {{", sw_name));
        self.e.indent();
        self.e.wln(&format!("public var value: {}", underlying_sw));
        for (fname, fty, range) in &b.members {
            let width = range.end() - range.start() + 1;
            let shift = range.start();
            let mask_val: u128 = if width >= 128 { u128::MAX } else { (1u128 << width) - 1 };
            let ret_ty = {
                let ty = self.e.module.lookup(*fty).unwrap();
                match &ty.kind {
                    TypeKind::Primitive(p) => self.swift_primitive(p).to_string(),
                    TypeKind::Enum(e) => self.swift_primitive(&e.ty).to_string(),
                    _ => "UInt32".to_string(),
                }
            };
            let fname_s = sanitize_ident(fname, "T");
            self.e.wln(&format!(
                "public func get_{}() -> {} {{ return {}((UInt64(truncatingIfNeeded: self.value) >> {}) & {}) }}",
                fname_s, ret_ty, ret_ty, shift, mask_val
            ));
            self.e.wln(&format!(
                "public mutating func set_{}(_ v: {}) {{ let cleared = UInt64(truncatingIfNeeded: self.value) & ~({} << {}); let nv = cleared | ((UInt64(truncatingIfNeeded: v) & {}) << {}); self.value = {}(truncatingIfNeeded: nv) }}",
                fname_s, ret_ty, mask_val, shift, mask_val, shift, underlying_sw
            ));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_pack(&mut self, name: &str, p: &Pack) {
        let sw_name = sanitize_ident(name, "T");
        self.e.wln(&format!("public struct {} {{", sw_name));
        self.e.indent();
        for (mname, mtid) in &p.members {
            let t = self.type_for_pack_field(*mtid);
            let fname = self.swift_ident(mname, "T");
            self.e.wln(&format!("public var {}: {}", fname, t));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_sequence_type(&mut self, name: &str, s: &Sequence) {
        let sw_name = sanitize_ident(name, "T");
        self.e.wln(&format!("public struct {} {{", sw_name));
        self.e.indent();
        for (mname, mtid) in &s.members {
            let t = self.type_for_seq_field(*mtid);
            let fname = self.swift_ident(mname, "T");
            self.e.wln(&format!("public var {}: {}", fname, t));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_variant_type(&mut self, name: &str, v: &Variant) {
        let sw_name = sanitize_ident(name, "T");
        self.e.wln(&format!("public enum {} {{", sw_name));
        self.e.indent();
        for (idx, (_val, vt)) in v.members.iter().enumerate() {
            let case_ty = self.type_for_seq_field(*vt);
            self.e.wln(&format!("case alt{}({})", idx, case_ty));
        }
        if let Some((_dfv, dftid)) = &v.default {
            let case_ty = self.type_for_seq_field(*dftid);
            self.e.wln(&format!("case defaultAlt({})", case_ty));
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_all_types(&mut self) {
        let order: Vec<TypeID> = self.e.module.type_order.clone();
        for tid in order.into_iter() {
            let Some(ty) = self.e.module.lookup(tid) else { continue };
            let Some(name) = self.e.name_of(tid).map(|x| x.to_string()) else { continue };
            if let Span::Builtin = ty.defined_at { continue; }

            match &ty.kind {
                TypeKind::Enum(e) => self.emit_enum(&name, e),
                TypeKind::Bitfld(b) => self.emit_bitfield(&name, b),
                TypeKind::Pack(p) => self.emit_pack(&name, p),
                TypeKind::Sequence(s) => self.emit_sequence_type(&name, s),
                TypeKind::Variant(v) => self.emit_variant_type(&name, v),
                TypeKind::Alias(_) => { /* not implemented for Swift */ }
                TypeKind::Primitive(_) | TypeKind::DynamicArray(_) | TypeKind::FixedArray(_) => {}
            }
            self.e.wln("");
            self.emit_read_fn(tid, &name);
            self.emit_write_fn(tid, &name);
            self.e.wln("");
        }
        self.emit_fixed_helpers();
        // close namespace
        self.e.dedent();
        let ns = sanitize_ident(&self.e.module.name, "Module");
        self.e.wln(&format!("}} // enum {}", ns));
    }

    fn fixed_data_type_name(&mut self, count: usize) -> String {
        self.fixed_datas.insert(count);
        format!("FixedData_{}", count)
    }

    fn fixed_array_type_name(&mut self, elem_sw: &str, count: usize) -> String {
        let key = (elem_sw.to_string(), count);
        if let Some(name) = self.fixed_arrays.get(&key) {
            return name.clone();
        }
        let name = format!("FixedArray_{}_{}", count, sanitize_ident(elem_sw, "T"));
        self.fixed_arrays.insert(key, name.clone());
        name
    }

    fn emit_fixed_helpers(&mut self) {
        // Emit FixedData wrappers
        let mut counts: Vec<_> = self.fixed_datas.iter().copied().collect();
        counts.sort_unstable();
        for n in counts {
            self.e.wln(&format!("public struct FixedData_{} {{", n));
            self.e.indent();
            self.e.wln("public var data: Data");
            self.e.wln(&format!("public init(_ d: Data) throws {{ guard d.count == {} else {{ throw JawError.lengthMismatch }}; self.data = d }}", n));
            self.e.wln(&format!("public var count: Int {{ {} }}", n));
            self.e.dedent();
            self.e.wln("}");
            self.e.wln("");
        }
        // Emit FixedArray wrappers
        let mut entries: Vec<_> = self.fixed_arrays.iter().collect();
        entries.sort_by(|a, b| a.1.cmp(b.1));
        for ((elem_sw, n), tyname) in entries.into_iter().map(|(k, v)| (k.clone(), v.clone())) {
            self.e.wln(&format!("public struct {} {{", tyname));
            self.e.indent();
            // Tuple storage
            let mut tuple = String::new();
            for i in 0..n {
                if i > 0 { tuple.push_str(", "); }
                tuple.push_str(&elem_sw);
            }
            self.e.wln(&format!("public var elements: ({})", tuple));
            self.e.wln(&format!("public init(_ arr: [{}]) throws {{", elem_sw));
            self.e.indent();
            self.e.wln(&format!("guard arr.count == {} else {{ throw JawError.lengthMismatch }}", n));
            let mut assigns = String::new();
            for i in 0..n {
                if i > 0 { assigns.push_str(", "); }
                assigns.push_str(&format!("arr[{}]", i));
            }
            self.e.wln(&format!("self.elements = ({})", assigns));
            self.e.dedent();
            self.e.wln("}");
            self.e.wln(&format!("public var count: Int {{ {} }}", n));
            let mut array_expr = String::from("[");
            for i in 0..n {
                if i > 0 { array_expr.push_str(", "); }
                array_expr.push_str(&format!("elements.{}", i));
            }
            array_expr.push(']');
            self.e.wln(&format!("public func asArray() -> [{}] {{ {} }}", elem_sw, array_expr));
            self.e.dedent();
            self.e.wln("}");
            self.e.wln("");
        }
    }

    fn emit_read_member(&mut self, tid: TypeID, lhs_ident: &str) {
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(p) => {
                let m = self.sw_read_prim(p);
                self.e.wln(&format!("let {} = try r.{}()", lhs_ident, m));
            }
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("read_{}", sanitize_ident(name, "T"));
                    self.e.wln(&format!("let {} = try Self.{}(&r)", lhs_ident, func));
                } else {
                    self.e.wln("throw JawError.anonymousType");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic { size_type, value_type })
            | TypeKind::FixedArray(ArrayKind::Dynamic { size_type, value_type }) => {
                let st = self.e.module.lookup(*size_type).unwrap();
                let sp = match &st.kind { TypeKind::Primitive(p) => p, _ => panic!("size_type not primitive") };
                let readm = self.sw_read_prim(sp);
                let vt = self.e.module.lookup(*value_type).unwrap();
                let is_u8 = matches!(vt.kind, TypeKind::Primitive(Primitive::U8));
                self.e.wln(&format!("let __n = Int(try r.{}())", readm));
                if is_u8 {
                    self.e.wln(&format!("let {} = try r.readBytes(__n)", lhs_ident));
                } else {
                    let elem_read = match &vt.kind {
                        TypeKind::Primitive(p) => format!("try r.{}()", self.sw_read_prim(p)),
                        _ => {
                            if let Some(name) = self.e.name_of(*value_type) {
                                format!("try Self.read_{}(&r)", sanitize_ident(name, "T"))
                            } else {
                                "throw JawError.anonymousType".to_string()
                            }
                        }
                    };
                    let elem_sw = match &vt.kind {
                        TypeKind::Primitive(p) => self.swift_primitive(p).to_string(),
                        _ => if let Some(name) = self.e.name_of(*value_type) { sanitize_ident(name, "T") } else { "Int32".to_string() },
                    };
                    self.e.wln(&format!("var {}: [{}] = []", lhs_ident, elem_sw));
                    self.e.wln("for _ in 0..<( __n ) {");
                    self.e.indent();
                    self.e.wln(&format!("{}.append({})", lhs_ident, elem_read));
                    self.e.dedent();
                    self.e.wln("}");
                }
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let vt = self.e.module.lookup(*value_type).unwrap();
                if matches!(vt.kind, TypeKind::Primitive(Primitive::U8)) {
                    let tyname = self.fixed_data_type_name(*count as usize);
                    self.e.wln(&format!("let {} = try {}(try r.readBytes({}))", lhs_ident, tyname, count));
                } else {
                    let elem_read = match &vt.kind {
                        TypeKind::Primitive(p) => format!("try r.{}()", self.sw_read_prim(p)),
                        _ => {
                            if let Some(name) = self.e.name_of(*value_type) {
                                format!("try Self.read_{}(&r)", sanitize_ident(name, "T"))
                            } else {
                                "throw JawError.anonymousType".to_string()
                            }
                        }
                    };
                    let elem_sw = match &vt.kind {
                        TypeKind::Primitive(p) => self.swift_primitive(p).to_string(),
                        _ => if let Some(name) = self.e.name_of(*value_type) { sanitize_ident(name, "T") } else { "Int32".to_string() },
                    };
                    self.e.wln(&format!("var __tmp: [{}] = []", elem_sw));
                    self.e.wln(&format!("for _ in 0..<{} {{", count));
                    self.e.indent();
                    self.e.wln(&format!("__tmp.append({})", elem_read));
                    self.e.dedent();
                    self.e.wln("}");
                    let arr_ty = self.fixed_array_type_name(&elem_sw, *count as usize);
                    self.e.wln(&format!("let {} = try {}(__tmp)", lhs_ident, arr_ty));
                }
            }
            TypeKind::Alias(_) => self.e.wln("throw JawError.anonymousType"),
        }
    }

    fn emit_write_member(&mut self, tid: TypeID, expr: &str) {
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(p) => {
                let m = self.sw_write_prim(p);
                self.e.wln(&format!("w.{}({})", m, expr));
            }
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.e.name_of(tid) {
                    let func = format!("write_{}", sanitize_ident(name, "T"));
                    self.e.wln(&format!("try Self.{}(&w, {})", func, expr));
                } else {
                    self.e.wln("throw JawError.anonymousType");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic { size_type, value_type })
            | TypeKind::FixedArray(ArrayKind::Dynamic { size_type, value_type }) => {
                let st = self.e.module.lookup(*size_type).unwrap();
                let sp = match &st.kind { TypeKind::Primitive(p) => p, _ => panic!("size_type not primitive") };
                let write_m = self.sw_write_prim(sp);
                let vt = self.e.module.lookup(*value_type).unwrap();
                let is_u8 = matches!(vt.kind, TypeKind::Primitive(Primitive::U8));
                self.e.wln(&format!("w.{}({}({}.count))", write_m, self.swift_primitive(sp), expr));
                if is_u8 {
                    self.e.wln(&format!("w.writeBytes({})", expr));
                } else {
                    self.e.wln(&format!("for __v in {} {{", expr));
                    self.e.indent();
                    self.emit_write_member(*value_type, "__v");
                    self.e.dedent();
                    self.e.wln("}");
                }
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let vt = self.e.module.lookup(*value_type).unwrap();
                if matches!(vt.kind, TypeKind::Primitive(Primitive::U8)) {
                    self.e.wln(&format!("w.writeBytes({}.data)", expr));
                } else {
                    self.e.wln(&format!("for __v in {}.asArray() {{", expr));
                    self.e.indent();
                    self.emit_write_member(*value_type, "__v");
                    self.e.dedent();
                    self.e.wln("}");
                }
            }
            TypeKind::Alias(_) => self.e.wln("throw JawError.anonymousType"),
        }
    }

    fn emit_read_fn(&mut self, tid: TypeID, name: &str) {
        let sw_name = sanitize_ident(name, "T");
        self.e.wln(&format!("public static func read_{}(_ r: inout Reader) throws -> {} {{", sw_name, sw_name));
        self.e.indent();
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Enum(e) => {
                let prim_fn = self.sw_read_prim(&e.ty);
                self.e.wln(&format!("let tmp = try r.{}()", prim_fn));
                if e.members.is_empty() && e.default.is_none() {
                    self.e.wln("throw JawError.invalidEnum");
                } else {
                    self.e.wln("switch tmp {");
                    self.e.indent();
                    for (mname, val) in &e.members {
                        let vname = sanitize_ident(mname, "T");
                        self.e.wln(&format!("case {}: return .{}", val, vname));
                    }
                    if let Some((dname, _)) = &e.default {
                        let vname = sanitize_ident(dname, "T");
                        self.e.wln(&format!("default: return .{}", vname));
                    } else {
                        self.e.wln("default: throw JawError.invalidEnum");
                    }
                    self.e.dedent();
                    self.e.wln("}");
                }
            }
            TypeKind::Bitfld(b) => {
                let underlying = self.e.module.lookup(b.ty).unwrap();
                let prim = match &underlying.kind { TypeKind::Primitive(p) => p, TypeKind::Enum(e) => &e.ty, _ => panic!("invalid bitfield base") };
                let prim_fn = self.sw_read_prim(prim);
                self.e.wln(&format!("let tmp = try r.{}()", prim_fn));
                self.e.wln(&format!("return {}(value: tmp)", sw_name));
            }
            TypeKind::Pack(p) => {
                for (mname, mtid) in &p.members {
                    let lhs = self.swift_ident(mname, "T");
                    self.emit_read_member(*mtid, &lhs);
                }
                self.e.wln(&format!("return {}(", sw_name));
                self.e.indent();
                for (mname, _mtid) in &p.members {
                    let lhs = self.swift_ident(mname, "T");
                    self.e.wln(&format!("{}: {},", lhs, lhs));
                }
                self.e.dedent();
                self.e.wln(")");
            }
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    let lhs = self.swift_ident(mname, "T");
                    self.emit_read_member(*mtid, &lhs);
                }
                self.e.wln(&format!("return {}(", sw_name));
                self.e.indent();
                for (mname, _mtid) in &s.members {
                    let lhs = self.swift_ident(mname, "T");
                    self.e.wln(&format!("{}: {},", lhs, lhs));
                }
                self.e.dedent();
                self.e.wln(")");
            }
            TypeKind::Variant(v) => {
                let prim_fn = self.sw_read_prim(&v.ty);
                self.e.wln(&format!("let tag = try r.{}()", prim_fn));
                if !v.members.is_empty() {
                    for (idx, (val, vt)) in v.members.iter().enumerate() {
                        self.e.wln(&format!("if tag == {} {{", val));
                        self.e.indent();
                        self.e.wln("do {");
                        self.e.indent();
                        // Read into __value then return
                        // Use a nested inout read via forwarding
                        self.emit_read_member(*vt, "__value");
                        self.e.wln(&format!("return .alt{}(__value)", idx));
                        self.e.dedent();
                        self.e.wln("}");
                        self.e.dedent();
                        self.e.wln("}");
                    }
                    if let Some((_dfv, dftid)) = &v.default {
                        self.emit_read_member(*dftid, "__value");
                        self.e.wln("return .defaultAlt(__value)");
                    } else {
                        self.e.wln("throw JawError.invalidVariant");
                    }
                } else if let Some((_dfv, dftid)) = &v.default {
                    self.emit_read_member(*dftid, "__value");
                    self.e.wln("return .defaultAlt(__value)");
                } else {
                    self.e.wln("throw JawError.invalidVariant");
                }
            }
            _ => self.e.wln("throw JawError.anonymousType"),
        }
        self.e.dedent();
        self.e.wln("}");
    }

    fn emit_write_fn(&mut self, tid: TypeID, name: &str) {
        let sw_name = sanitize_ident(name, "T");
        self.e.wln(&format!("public static func write_{}(_ w: inout Writer, _ v: {}) throws {{", sw_name, sw_name));
        self.e.indent();
        let ty = self.e.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Enum(e) => {
                // Write raw value
                let prim = &e.ty;
                let m = self.sw_write_prim(prim);
                self.e.wln(&format!("w.{}(v.rawValue)", m));
            }
            TypeKind::Bitfld(b) => {
                let underlying = self.e.module.lookup(b.ty).unwrap();
                let prim = match &underlying.kind { TypeKind::Primitive(p) => p, TypeKind::Enum(e) => &e.ty, _ => panic!("invalid bitfield base") };
                let m = self.sw_write_prim(prim);
                self.e.wln(&format!("w.{}(v.value)", m));
            }
            TypeKind::Pack(p) => {
                for (mname, mtid) in &p.members {
                    let expr = format!("v.{}", self.swift_ident(mname, "T"));
                    self.emit_write_member(*mtid, &expr);
                }
            }
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    let expr = format!("v.{}", self.swift_ident(mname, "T"));
                    self.emit_write_member(*mtid, &expr);
                }
            }
            TypeKind::Variant(v) => {
                let m = self.sw_write_prim(&v.ty);
                if !v.members.is_empty() {
                    self.e.wln("switch v {");
                    self.e.indent();
                    for (idx, (val, vt)) in v.members.iter().enumerate() {
                        self.e.wln(&format!("case .alt{}(let __x):", idx));
                        self.e.indent();
                        self.e.wln(&format!("w.{}({})", m, val));
                        self.emit_write_member(*vt, "__x");
                        self.e.wln("return");
                        self.e.dedent();
                    }
                    if let Some((_dfv, dt)) = &v.default {
                        self.e.wln("case .defaultAlt(let __x):");
                        self.e.indent();
                        // write tag for default case: use provided DFV
                        self.e.wln(&format!("w.{}({})", m, _dfv));
                        self.emit_write_member(*dt, "__x");
                        self.e.wln("return");
                        self.e.dedent();
                    }
                    self.e.dedent();
                    self.e.wln("}");
                    self.e.wln("throw JawError.invalidVariant");
                } else if let Some((_dfv, dt)) = &v.default {
                    self.e.wln(&format!("w.{}({})", m, _dfv));
                    self.emit_write_member(*dt, "v");
                } else {
                    self.e.wln("throw JawError.invalidVariant");
                }
            }
            _ => self.e.wln("throw JawError.anonymousType"),
        }
        self.e.dedent();
        self.e.wln("}");
    }
}
