// Generated by jaw. Do not edit.
#pragma once
#include <cstdint>
#include <vector>
#include <array>
#include <variant>
#include <span>

// Reader/Writer requirements:
// bool write_{u|i}{8|16|32|64}(T)
// bool write_{f}{32|64}(T)
// bool write_raw(T const&)
// bool  read_{u|i}{8|16|32|64}(T&)
// bool  read_{f}{32|64}(T&)
// bool  read_raw(T&)
// C++20 required (std::span, std::variant). Endianness left to Reader/Writer.

namespace basic {
    namespace detail {
        template <typename Reader> inline bool read_prim(Reader& r, uint8_t& v) { return r.read_u8(v); }
        template <typename Reader> inline bool read_prim(Reader& r, uint16_t& v) { return r.read_u16(v); }
        template <typename Reader> inline bool read_prim(Reader& r, uint32_t& v) { return r.read_u32(v); }
        template <typename Reader> inline bool read_prim(Reader& r, uint64_t& v) { return r.read_u64(v); }
        template <typename Reader> inline bool read_prim(Reader& r, int8_t& v) { return r.read_i8(v); }
        template <typename Reader> inline bool read_prim(Reader& r, int16_t& v) { return r.read_i16(v); }
        template <typename Reader> inline bool read_prim(Reader& r, int32_t& v) { return r.read_i32(v); }
        template <typename Reader> inline bool read_prim(Reader& r, int64_t& v) { return r.read_i64(v); }
        template <typename Reader> inline bool read_prim(Reader& r, float& v) { return r.read_f32(v); }
        template <typename Reader> inline bool read_prim(Reader& r, double& v) { return r.read_f64(v); }
        template <typename Reader, typename T> inline bool read_raw(Reader& r, T& v) { return r.read_raw(v); }
        
        template <typename Writer> inline bool write_prim(Writer& w, uint8_t v) { return w.write_u8(v); }
        template <typename Writer> inline bool write_prim(Writer& w, uint16_t v) { return w.write_u16(v); }
        template <typename Writer> inline bool write_prim(Writer& w, uint32_t v) { return w.write_u32(v); }
        template <typename Writer> inline bool write_prim(Writer& w, uint64_t v) { return w.write_u64(v); }
        template <typename Writer> inline bool write_prim(Writer& w, int8_t v) { return w.write_i8(v); }
        template <typename Writer> inline bool write_prim(Writer& w, int16_t v) { return w.write_i16(v); }
        template <typename Writer> inline bool write_prim(Writer& w, int32_t v) { return w.write_i32(v); }
        template <typename Writer> inline bool write_prim(Writer& w, int64_t v) { return w.write_i64(v); }
        template <typename Writer> inline bool write_prim(Writer& w, float v) { return w.write_f32(v); }
        template <typename Writer> inline bool write_prim(Writer& w, double v) { return w.write_f64(v); }
        template <typename Writer, typename T> inline bool write_raw(Writer& w, T const& v) { return w.write_raw(v); }
    } // namespace detail
    
    enum class BetterEnum : uint8_t {
        A = 0,
        B = 1,
        DEFAULT = 255,
    };
    
    template <typename Reader> inline bool read(Reader& r, BetterEnum& out) {
        uint8_t tmp{};
        if (!detail::read_prim(r, tmp)) return false;
        switch (tmp) {
            case 0 : out = BetterEnum::A; break;
            case 1 : out = BetterEnum::B; break;
            default: out = BetterEnum::DEFAULT;
        }
        return true;
    }
    template <typename Writer> inline bool write(Writer& w, const BetterEnum& in) {
        uint8_t tmp = static_cast<uint8_t>(in);
        return detail::write_prim(w, tmp);
    }
    
    enum class PlainEnum : uint8_t {
        F1 = 0,
        F2 = 1,
    };
    
    template <typename Reader> inline bool read(Reader& r, PlainEnum& out) {
        uint8_t tmp{};
        if (!detail::read_prim(r, tmp)) return false;
        out = static_cast<PlainEnum>(tmp);
        return true;
    }
    template <typename Writer> inline bool write(Writer& w, const PlainEnum& in) {
        uint8_t tmp = static_cast<uint8_t>(in);
        return detail::write_prim(w, tmp);
    }
    
    struct MyPOD {
        uint8_t a_thing;
        uint64_t b_thing;
    };
    
    template <typename Reader> inline bool read(Reader& r, MyPOD& out) {
        return r.read_raw(out);
    }
    template <typename Writer> inline bool write(Writer& w, const MyPOD& in) {
        return w.write_raw(in);
    }
    
    struct MyFlags {
        uint8_t value{};
        inline uint8_t get_is_thing() const { return static_cast<uint8_t>((value >> 0) & (1ULL)); }
        inline void set_is_thing(uint8_t v) { value = static_cast<uint8_t>((value & ~((1ULL) << 0)) | ((static_cast<uint8_t>(v) & (1ULL)) << 0)); }
        inline uint8_t get_another_thing() const { return static_cast<uint8_t>((value >> 1) & (3ULL)); }
        inline void set_another_thing(uint8_t v) { value = static_cast<uint8_t>((value & ~((3ULL) << 1)) | ((static_cast<uint8_t>(v) & (3ULL)) << 1)); }
        inline PlainEnum get_some_stuff() const { return static_cast<PlainEnum>((value >> 3) & (3ULL)); }
        inline void set_some_stuff(PlainEnum v) { value = static_cast<uint8_t>((value & ~((3ULL) << 3)) | ((static_cast<uint8_t>(v) & (3ULL)) << 3)); }
    };
    
    template <typename Reader> inline bool read(Reader& r, MyFlags& out) {
        uint8_t tmp{};
        if (!detail::read_prim(r, tmp)) return false;
        out.value = tmp;
        return true;
    }
    template <typename Writer> inline bool write(Writer& w, const MyFlags& in) {
        return detail::write_prim(w, in.value);
    }
    
    struct MyOtherPOD {
        MyPOD first;
        std::array<uint8_t, 4> second;
    };
    
    template <typename Reader> inline bool read(Reader& r, MyOtherPOD& out) {
        return r.read_raw(out);
    }
    template <typename Writer> inline bool write(Writer& w, const MyOtherPOD& in) {
        return w.write_raw(in);
    }
    
    struct MyObject {
        std::vector<uint8_t> name;
        MyOtherPOD pod;
    };
    struct MyObjectView {
        std::span<const uint8_t> name;
        const MyOtherPOD& pod;
    };
    
    template <typename Reader> inline bool read(Reader& r, MyObject& out) {
        {
            uint8_t __n{};
            if (!detail::read_prim(r, __n)) return false;
            out.name.clear(); out.name.resize(static_cast<size_t>(__n));
            for (size_t i = 0; i < static_cast<size_t>(__n); ++i) {
                if (!detail::read_prim(r, out.name[i])) return false;
            }
        }
        if (!read(r, out.pod)) return false;
        return true;
    }
    template <typename Writer> inline bool write(Writer& w, const MyObject& in) {
        {
            uint8_t __n = static_cast<uint8_t>(in.name.size());
            if (!detail::write_prim(w, __n)) return false;
            for (size_t i = 0; i < in.name.size(); ++i) {
                if (!detail::write_prim(w, in.name[i])) return false;
            }
        }
        if (!write(w, in.pod)) return false;
        return true;
    }
    template <typename Writer> inline bool write(Writer& w, const MyObjectView& in) {
        {
            uint8_t __n = static_cast<uint8_t>(in.name.size());
            if (!detail::write_prim(w, __n)) return false;
            for (size_t i = 0; i < in.name.size(); ++i) {
                if (!detail::write_prim(w, in.name[i])) return false;
            }
        }
        if (!write(w, in.pod)) return false;
        return true;
    }
    
    struct MyVariant { std::variant<MyPOD, MyOtherPOD, MyObject> value; };
    struct MyVariantView { std::variant<MyPOD const* , MyOtherPOD const* , MyObject const* > value; };
    
    template <typename Reader> inline bool read(Reader& r, MyVariant& out) {
        uint8_t tag{};
        if (!detail::read_prim(r, tag)) return false;
        switch (static_cast<decltype(tag)>(tag)) {
            case 0: {
                MyPOD& tmp = out.value.emplace<0>();
                if (!read(r, tmp)) return false;
                return true;
            }
            case 1: {
                MyOtherPOD& tmp = out.value.emplace<1>();
                if (!read(r, tmp)) return false;
                return true;
            }
            default: {
                MyObject& tmp = out.value.emplace<2>();
                if (!read(r, tmp)) return false;
                return true;
            }
        }
        return true;
    }
    template <typename Writer> inline bool write(Writer& w, const MyVariant& in) {
        uint8_t tag = in.value.index();
        if (!detail::write_prim(w, tag)) return false;
        switch (tag) {
            case 0: {
                const auto& ptr = std::get<0>(in.value);
                if (!write(w, ptr)) return false;
                return true;
            }
            case 1: {
                const auto& ptr = std::get<1>(in.value);
                if (!write(w, ptr)) return false;
                return true;
            }
            default: {
                const auto& ptr = std::get<2>(in.value);
                if (!write(w, ptr)) return false;
                return true;
            }
        }
        return true;
    }
    template <typename Writer> inline bool write(Writer& w, const MyVariantView& in) {
        uint8_t tag = in.value.index();
        if (!detail::write_prim(w, tag)) return false;
        switch (tag) {
            case 0: {
                auto ptr = std::get<0>(in.value);
                if (!write(w, *ptr)) return false;
                return true;
            }
            case 1: {
                auto ptr = std::get<1>(in.value);
                if (!write(w, *ptr)) return false;
                return true;
            }
            default: {
                auto ptr = std::get<2>(in.value);
                if (!write(w, *ptr)) return false;
                return true;
            }
        }
        return true;
    }
    
} // namespace basic
