use crate::module::*;
use std::fmt::Write as _;

// Public entry: emit a single header string with all types and read/write helpers
pub fn emit_cpp_header(module: Module) -> String {
    let mut e = CppEmitter::new(&module);
    e.emit_preamble();
    e.emit_all_types();
    e.finish()
}

struct CppEmitter<'a> {
    module: &'a Module,
    out: String,
    indent: usize,
}

impl<'a> CppEmitter<'a> {
    fn new(module: &'a Module) -> Self {
        Self {
            module,
            out: String::new(),
            indent: 0,
        }
    }

    fn finish(self) -> String {
        self.out
    }

    fn wln(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn w(&mut self, s: &str) {
        self.out.push_str(s);
    }

    fn indent(&mut self) {
        self.indent += 1;
    }

    fn dedent(&mut self) {
        assert!(self.indent > 0);
        self.indent -= 1;
    }

    fn is_named_type(&self, tid: TypeID) -> bool {
        self.module.inv_type_map.contains_key(&tid)
    }

    fn name_of(&self, tid: TypeID) -> Option<&str> {
        self.module.inv_type_map.get(&tid).map(|s| s.as_str())
    }

    fn emit_preamble(&mut self) {
        let ns = Self::sanitize_namespace(&self.module.name);
        self.wln("// Generated by jaw. Do not edit.");
        self.wln("#pragma once");
        self.wln("#include <cstdint>");
        self.wln("#include <vector>");
        self.wln("#include <array>");
        self.wln("#include <variant>");
        self.wln("#include <span>");
        self.wln("");
        self.wln("// Reader/Writer requirements:");
        self.wln("// bool write_{u|i}{8|16|32|64}(T)");
        self.wln("// bool write_{f}{32|64}(T)");
        self.wln("// bool write_raw(T const&)");
        self.wln("// bool  read_{u|i}{8|16|32|64}(T&)");
        self.wln("// bool  read_{f}{32|64}(T&)");
        self.wln("// bool  read_raw(T&)");
        self.wln("// C++20 required (std::span, std::variant). Endianness left to Reader/Writer.");
        self.wln("");
        self.wln(&format!("namespace {} {{", ns));
        self.indent();
        self.wln("namespace detail {");
        self.indent();
        // Helpers for primitives
        self.wln("template <typename Reader, typename T> inline bool read_raw(Reader& r, T& v) { return r.read_raw(v); }");
        self.wln("");
        self.wln("template <typename Writer, typename T> inline bool write_raw(Writer& w, T const& v) { return w.write_raw(v); }");
        self.dedent();
        self.wln("} // namespace detail");
        self.wln("");
    }

    fn emit_all_types(&mut self) {
        // Generate type declarations and read/write functions in topological order.
        // Only generate concrete definitions for named, user-defined types (skip builtins and anonymous inline types).
        let order: Vec<TypeID> = self.module.type_order.clone();
        for tid in order.into_iter() {
            let Some(ty) = self.module.lookup(tid) else {
                continue;
            };
            let Some(name_owned) = self.name_of(tid).map(|x| x.to_string()) else {
                continue;
            };
            // Skip builtins: defined_at == None
            if ty.defined_at.is_none() {
                continue;
            }

            match &ty.kind {
                TypeKind::Enum(e) => self.emit_enum(&name_owned, e),
                TypeKind::Bitfld(b) => self.emit_bitfield(&name_owned, b),
                TypeKind::Pack(p) => {
                    self.emit_pack(&name_owned, p);
                }
                TypeKind::Sequence(s) => {
                    self.emit_sequence_type(&name_owned, s);
                    self.emit_sequence_view(&name_owned, s);
                }
                TypeKind::Variant(v) => self.emit_variant(&name_owned, v),
                TypeKind::Alias(inner) => self.emit_alias(&name_owned, inner),
                TypeKind::Primitive(_) => { /* already skipped by defined_at */ }
                TypeKind::DynamicArray(_) | TypeKind::FixedArray(_) => {
                    // Do not emit top-level for anonymous arrays; arrays should not be named top-level here.
                }
            }
            self.wln("");
            // Readers and Writers
            self.emit_read_fn(tid, &name_owned);
            self.emit_write_fn(tid, &name_owned);
            if matches!(ty.kind, TypeKind::Sequence(_) | TypeKind::Variant(_)) {
                self.emit_write_fn_view(tid, &name_owned);
            }
            self.wln("");
        }

        // close namespaces
        self.dedent();
        let ns = Self::sanitize_namespace(&self.module.name);
        self.wln(&format!("}} // namespace {}", ns));
    }

    fn sanitize_namespace(raw: &str) -> String {
        let mut s = String::new();
        for (i, ch) in raw.chars().enumerate() {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                if i == 0 && ch.is_ascii_digit() {
                    s.push('_');
                }
                s.push(ch);
            } else {
                if i == 0 {
                    s.push('_');
                }
                s.push('_');
            }
        }
        if s.is_empty() {
            s.push_str("module");
        }
        s
    }

    fn emit_enum(&mut self, name: &str, e: &Enum) {
        let underlying = self.cpp_primitive(&e.ty);
        self.wln(&format!("enum class {} : {} {{", name, underlying));
        self.indent();
        for (i, (mname, val)) in e.members.iter().enumerate() {
            self.wln(&format!("{} = {},", mname, val));
        }
        if let Some((dname, dval)) = &e.default {
            self.wln(&format!("{} = {},", dname, dval));
        }
        self.dedent();
        self.wln("};");
    }

    fn emit_bitfield(&mut self, name: &str, b: &Bitfld) {
        let underlying_tid = b.ty;
        let underlying_cpp = self.cpp_type_owned(underlying_tid);
        self.wln(&format!("struct {} {{", name));
        self.indent();
        self.wln(&format!("{} value{{}};", underlying_cpp));
        // Getters and setters
        for (fname, fty, range) in &b.members {
            let width = range.end() - range.start() + 1;
            let shift = range.start();
            let mask_val: u128 = if width >= 128 {
                u128::MAX
            } else {
                (1u128 << width) - 1
            };
            let mut mask_lit = String::new();
            if width >= 64 {
                // emit as 128 then cast
                write!(mask_lit, "{}ULL", mask_val as u64).unwrap();
            } else {
                // up to 63 bits safe in 64-bit literal
                write!(mask_lit, "{}ULL", (mask_val as u64)).unwrap();
            }
            let ret_ty = self.cpp_type_owned(*fty);
            self.wln(&format!(
                "inline {} get_{}() const {{ return static_cast<{}>((value >> {}) & ({})); }}",
                ret_ty, fname, ret_ty, shift, mask_lit
            ));
            self.wln(&format!(
                "inline void set_{}({} v) {{ value = static_cast<{}>((value & ~(({}) << {})) | ((static_cast<{}>(v) & ({})) << {})); }}",
                fname,
                ret_ty,
                underlying_cpp,
                mask_lit,
                shift,
                underlying_cpp,
                mask_lit,
                shift
            ));
        }
        self.dedent();
        self.wln("};");
    }

    fn emit_pack(&mut self, name: &str, p: &Pack) {
        self.wln(&format!("struct {} {{", name));
        self.indent();
        for (mname, mtid) in &p.members {
            let t = self.cpp_type_owned(*mtid);
            self.wln(&format!("{} {};", t, mname));
        }
        self.dedent();
        self.wln("};");
    }

    fn emit_sequence_type(&mut self, name: &str, s: &Sequence) {
        self.wln(&format!("struct {} {{", name));
        self.indent();
        for (mname, mtid) in &s.members {
            let t = self.cpp_type_owned(*mtid);
            self.wln(&format!("{} {};", t, mname));
        }
        self.dedent();
        self.wln("};");
    }

    fn emit_sequence_view(&mut self, name: &str, s: &Sequence) {
        let vname = format!("{}View", name);
        self.wln(&format!("struct {} {{", vname));
        self.indent();
        for (mname, mtid) in &s.members {
            let t = self.cpp_type_view_field(*mtid);
            self.wln(&format!("{} {};", t, mname));
        }
        self.dedent();
        self.wln("};");
    }

    fn emit_variant(&mut self, name: &str, v: &Variant) {
        //let discr_ty = self.cpp_type_owned(v.ty);
        // collect alternative types in declaration order
        let mut alt_types: Vec<String> = Vec::new();
        let mut alt_ref_types: Vec<String> = Vec::new();
        for (_, tid) in &v.members {
            let mut r = self.cpp_type_owned(*tid);
            alt_types.push(r.clone());
            r.push_str(" const* ");
            alt_ref_types.push(r);
        }
        if let Some((_, dftid)) = &v.default {
            let mut r = self.cpp_type_owned(*dftid);
            alt_types.push(r.clone());
            r.push_str(" const* ");
            alt_ref_types.push(r);
        }
        let alts = if alt_types.is_empty() {
            String::from("std::monostate")
        } else {
            alt_types.join(", ")
        };

        let alt_refs = if alt_ref_types.is_empty() {
            String::from("std::monostate")
        } else {
            alt_ref_types.join(", ")
        };

        self.wln(&format!(
            "struct {} {{ std::variant<{}> value; }};",
            name, alts
        ));

        self.wln(&format!(
            "struct {}View {{ std::variant<{}> value; }};",
            name, alt_refs
        ));
    }

    fn emit_alias(&mut self, name: &str, inner: &Type) {
        // Treat alias as using-declaration in C++
        let ty = self.cpp_type_from_type(inner);
        self.wln(&format!("using {} = {};", name, ty));
    }

    fn emit_read_fn(&mut self, tid: TypeID, name: &str) {
        // Definition
        self.wln(&format!(
            "template <typename Reader> inline bool read(Reader& r, {}& out) {{",
            name
        ));
        self.indent();
        let ty = self.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Enum(e) => {
                let u = self.cpp_primitive(&e.ty);
                self.wln(&format!("{} tmp{{}};", u));
                self.wln("if (!detail::read_raw(r, tmp)) return false;");

                if let Some(def) = &e.default {
                    // slow mode
                    self.wln("switch (tmp) {");
                    self.indent();

                    for mem in &e.members {
                        self.wln(&format!("case {} : out = {name}::{}; break;", mem.1, mem.0));
                    }

                    self.wln(&format!("default: out = {name}::{};", def.0));
                    self.dedent();
                    self.wln("}");
                } else {
                    //fast mode
                    self.wln(&format!("out = static_cast<{name}>(tmp);"));
                }

                self.wln("return true;");
            }
            TypeKind::Bitfld(b) => {
                let u = self.cpp_type_owned(b.ty);
                self.wln(&format!("{} tmp{{}};", u));
                self.wln("if (!detail::read_raw(r, tmp)) return false;");
                self.wln("out.value = tmp;");
                self.wln("return true;");
            }
            TypeKind::Pack(_) => {
                self.wln("return r.read_raw(out);");
            }
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    self.emit_read_member(*mtid, &format!("out.{}", mname));
                }
                self.wln("return true;");
            }
            TypeKind::Variant(v) => {
                let discr_ty = self.cpp_primitive(&v.ty);
                self.wln(&format!("{} tag{{}};", discr_ty));
                self.wln("if (!detail::read_raw(r, tag)) return false;");
                self.wln("switch (static_cast<decltype(tag)>(tag)) {");
                self.indent();
                for (val, vt) in &v.members {
                    self.wln(&format!("case {}: {{", val));
                    self.indent();
                    let val_cpp = self.cpp_type_owned(*vt);
                    self.wln(&format!("{}& tmp = out.value.emplace<{}>();", val_cpp, val));
                    self.emit_read_member(*vt, "tmp");
                    self.wln("return true;");
                    self.dedent();
                    self.wln("}");
                }
                if let Some((dfval, dftid)) = &v.default {
                    self.wln("default: {");
                    self.indent();
                    let val_cpp = self.cpp_type_owned(*dftid);
                    self.wln(&format!(
                        "{}& tmp = out.value.emplace<{}>();",
                        val_cpp, dfval
                    ));
                    self.emit_read_member(*dftid, "tmp");
                    self.wln("return true;");
                    self.dedent();
                    self.wln("}");
                } else {
                    self.wln("default: return false;");
                }
                self.dedent();
                self.wln("}");
                self.wln("return true;");
            }
            _ => {
                // Arrays should not be top-level named; primitives are excluded.
                self.wln("return false;");
            }
        }
        self.dedent();
        self.wln("}");
    }

    fn emit_write_fn(&mut self, tid: TypeID, name: &str) {
        self.wln(&format!(
            "template <typename Writer> inline bool write(Writer& w, const {}& in) {{",
            name
        ));
        self.indent();
        let ty = self.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Enum(e) => {
                let u = self.cpp_primitive(&e.ty);
                self.wln(&format!("{} tmp = static_cast<{}>(in);", u, u));
                self.wln("return detail::write_raw(w, tmp);");
            }
            TypeKind::Bitfld(b) => {
                self.wln("return detail::write_raw(w, in.value);");
            }
            TypeKind::Pack(p) => {
                self.wln("return w.write_raw(in);");
            }
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    self.emit_write_member(*mtid, &format!("in.{}", mname));
                }
                self.wln("return true;");
            }
            TypeKind::Variant(v) => {
                // Write tag then payload matching active alternative
                let ty = self.cpp_primitive(&v.ty);
                self.wln(&format!("{} tag = in.value.index();", ty));
                self.wln("if (!detail::write_raw(w, tag)) return false;");
                self.wln("switch (tag) {");
                self.indent();
                for (val, vt) in &v.members {
                    self.wln(&format!("case {}: {{", val));
                    self.indent();
                    self.wln(&format!("const auto& ptr = std::get<{}>(in.value);", val));
                    self.emit_write_member(*vt, "ptr");
                    self.wln("return true;");
                    self.dedent();
                    self.wln("}");
                }
                if let Some((dfval, dftid)) = &v.default {
                    self.wln("default: {");
                    self.indent();
                    self.wln(&format!("const auto& ptr = std::get<{}>(in.value);", dfval));
                    self.emit_write_member(*dftid, "ptr");
                    self.wln("return true;");
                    self.dedent();
                    self.wln("}");
                } else {
                    self.wln("default: return false;");
                }
                self.dedent();
                self.wln("}");
                self.wln("return true;");
            }
            _ => {
                self.wln("return false;");
            }
        }
        self.dedent();
        self.wln("}");
    }

    fn emit_write_fn_view(&mut self, tid: TypeID, name: &str) {
        let vname = format!("{}View", name);
        self.wln(&format!(
            "template <typename Writer> inline bool write(Writer& w, const {}& in) {{",
            vname
        ));
        self.indent();
        let ty = self.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Sequence(s) => {
                for (mname, mtid) in &s.members {
                    self.emit_write_member(*mtid, &format!("in.{}", mname));
                }
                self.wln("return true;");
            }
            TypeKind::Variant(v) => {
                // Write tag then payload matching active alternative
                let ty = self.cpp_primitive(&v.ty);
                self.wln(&format!("{} tag = in.value.index();", ty));
                self.wln("if (!detail::write_raw(w, tag)) return false;");
                self.wln("switch (tag) {");
                self.indent();
                for (val, vt) in &v.members {
                    self.wln(&format!("case {}: {{", val));
                    self.indent();
                    self.wln(&format!("auto ptr = std::get<{}>(in.value);", val));
                    self.emit_write_member(*vt, "*ptr");
                    self.wln("return true;");
                    self.dedent();
                    self.wln("}");
                }
                if let Some((dfval, dftid)) = &v.default {
                    self.wln("default: {");
                    self.indent();
                    self.wln(&format!("auto ptr = std::get<{}>(in.value);", dfval));
                    self.emit_write_member(*dftid, "*ptr");
                    self.wln("return true;");
                    self.dedent();
                    self.wln("}");
                } else {
                    self.wln("default: return false;");
                }
                self.dedent();
                self.wln("}");
                self.wln("return true;");
            }
            _ => {
                self.wln("return false;");
            }
        }
        self.dedent();
        self.wln("}");
    }

    fn emit_read_member(&mut self, tid: TypeID, lhs: &str) {
        let ty = self.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(_p) => {
                self.wln(&format!("if (!detail::read_raw(r, {})) return false;", lhs));
            }
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if self.name_of(tid).is_some() {
                    self.wln(&format!("if (!read(r, {})) return false;", lhs));
                } else {
                    // Anonymous composite, should not occur except arrays; fallback false
                    self.wln("return false;");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            }) => {
                // read size then elements
                self.wln("{");
                {
                    self.indent();
                    let size_cpp = self.cpp_type_owned(*size_type);
                    self.wln(&format!("{} __n{{}};", size_cpp));
                    self.wln("if (!detail::read_raw(r, __n)) return false;");
                    self.wln(&format!(
                        "{}.clear(); {}.resize(static_cast<size_t>(__n));",
                        lhs, lhs
                    ));
                    self.wln("for (size_t i = 0; i < static_cast<size_t>(__n); ++i) {");
                    self.indent();
                    let elem_lhs = format!("{}[i]", lhs);
                    self.emit_read_member(*value_type, &elem_lhs);
                    self.dedent();
                    self.wln("}");
                    self.dedent();
                }
                self.wln("}");
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                self.wln(&format!("for (size_t i = 0; i < {}; ++i) {{", count));
                self.indent();
                let elem_lhs = format!("{}[i]", lhs);
                self.emit_read_member(*value_type, &elem_lhs);
                self.dedent();
                self.wln("}");
            }
            TypeKind::Alias(inner) => {
                // read inner form directly
                let tmp_tid = tid; // not used distinctively here
                let _ = tmp_tid;
                // Fallback: not expected until alias parsing is implemented
                let inner_ty = self.cpp_type_from_type(inner);
                self.wln(&format!(
                    "// alias fallback; reading as inner type {};\n(void)sizeof({});",
                    inner_ty, inner_ty
                ));
                self.wln("return false;");
            }
        }
    }

    fn emit_write_member(&mut self, tid: TypeID, expr: &str) {
        let ty = self.module.lookup(tid).unwrap();
        match &ty.kind {
            TypeKind::Primitive(_) => {
                // rely on overload resolution via expr type
                self.wln(&format!(
                    "if (!detail::write_raw(w, {})) return false;",
                    expr
                ));
            }
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if self.name_of(tid).is_some() {
                    self.wln(&format!("if (!write(w, {})) return false;", expr));
                } else {
                    self.wln("return false;");
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type,
                value_type,
            }) => {
                self.wln("{");
                self.indent();
                {
                    // write size then elements
                    let size_cpp = self.cpp_type_owned(*size_type);
                    self.wln(&format!(
                        "{} __n = static_cast<{}>({}.size());",
                        size_cpp, size_cpp, expr
                    ));
                    self.wln("if (!detail::write_raw(w, __n)) return false;");
                    self.wln(&format!("for (size_t i = 0; i < {}.size(); ++i) {{", expr));
                    self.indent();
                    let elem_expr = format!("{}[i]", expr);
                    self.emit_write_member(*value_type, &elem_expr);
                    self.dedent();
                    self.wln("}");
                }
                self.dedent();
                self.wln("}");
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                self.wln(&format!("for (size_t i = 0; i < {}; ++i) {{", count));
                self.indent();
                let elem_expr = format!("{}[i]", expr);
                self.emit_write_member(*value_type, &elem_expr);
                self.dedent();
                self.wln("}");
            }
            TypeKind::Alias(inner) => {
                let inner_ty = self.cpp_type_from_type(inner);
                self.wln(&format!(
                    "// alias fallback; writing as inner type {};\n(void)sizeof({});",
                    inner_ty, inner_ty
                ));
                self.wln("return false;");
            }
        }
    }

    fn cpp_primitive(&self, p: &Primitive) -> String {
        match p {
            Primitive::U8 => "uint8_t".into(),
            Primitive::U16 => "uint16_t".into(),
            Primitive::U32 => "uint32_t".into(),
            Primitive::U64 => "uint64_t".into(),
            Primitive::I8 => "int8_t".into(),
            Primitive::I16 => "int16_t".into(),
            Primitive::I32 => "int32_t".into(),
            Primitive::I64 => "int64_t".into(),
            Primitive::F32 => "float".into(),
            Primitive::F64 => "double".into(),
        }
    }

    fn cpp_type_owned(&self, tid: TypeID) -> String {
        let ty = self.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.cpp_primitive(p),
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.name_of(tid) {
                    name.to_string()
                } else {
                    // anonymous composite should not be referenced directly; fallback
                    "/*anon*/int".to_string()
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::vector<{}>", elem)
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::array<{}, {}>", elem, count)
            }
            TypeKind::Alias(inner) => self.cpp_type_from_type(inner),
        }
    }

    fn cpp_type_from_type(&self, ty: &Type) -> String {
        match &ty.kind {
            TypeKind::Primitive(p) => self.cpp_primitive(p),
            TypeKind::Enum(_)
            | TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                // cannot get TypeID from Type directly to find its name; used only for alias right now
                "/*alias_target*/int".to_string()
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::vector<{}>", elem)
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::array<{}, {}>", elem, count)
            }
            TypeKind::Alias(inner) => self.cpp_type_from_type(inner),
        }
    }

    fn cpp_type_view_field(&self, tid: TypeID) -> String {
        let ty = self.module.lookup(tid).expect("unknown type");
        match &ty.kind {
            TypeKind::Primitive(p) => self.cpp_primitive(p),
            TypeKind::Enum(_) => {
                if let Some(name) = self.name_of(tid) {
                    name.to_string()
                } else {
                    "int".to_string()
                }
            }
            TypeKind::Bitfld(_)
            | TypeKind::Pack(_)
            | TypeKind::Sequence(_)
            | TypeKind::Variant(_) => {
                if let Some(name) = self.name_of(tid) {
                    format!("const {}&", name)
                } else {
                    "/*anon_ref*/int".to_string()
                }
            }
            TypeKind::DynamicArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            })
            | TypeKind::FixedArray(ArrayKind::Dynamic {
                size_type: _,
                value_type,
            }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::span<const {}>", elem)
            }
            TypeKind::FixedArray(ArrayKind::Fixed { count, value_type })
            | TypeKind::DynamicArray(ArrayKind::Fixed { count, value_type }) => {
                let elem = self.cpp_type_owned(*value_type);
                format!("std::span<const {}, {}>", elem, count)
            }
            TypeKind::Alias(inner) => {
                let base = self.cpp_type_from_type(inner);
                format!("const {}&", base)
            }
        }
    }
}
